#!/usr/bin/env python3
"""
gd-review-router.py — Plan 5 v3 Wave B

Unified /gd review state machine router.

Modes (--mode, required):
  fixture       Replay a pre-recorded fixture from fixtures/review-router-v2/.
  detect_only   Real target detection; no review invoked; writes route report.
  live_dry_run  Real detection + mock bridge wrapper; writes route report with mock flag.
  live          Full production run (requires Codex bridge available).

Route report:
  After every run the router writes a route_report.json and immediately validates
  it via scripts/gd-validate-route-report.py (SSOT). Consumers must verify
  validator_signature before trusting the report (Q2).

Q3 side-door prevention:
  The env var GD_REVIEW_ROUTER_INVOCATION_ID must NOT be set when invoking the router
  directly (it is only set BY the router for downstream scripts it spawns). A non-empty
  env value on entry signals an attempted side-door bypass and causes exit 2.

CLI:
  python3 scripts/gd-review-router.py --mode fixture --fixture <path.json> [--output-dir <dir>]
  python3 scripts/gd-review-router.py --mode detect_only [--target <path>] [--output-dir <dir>]
  python3 scripts/gd-review-router.py --mode live_dry_run [--target <path>] [--output-dir <dir>]
  python3 scripts/gd-review-router.py --mode live [--target <path>] [--output-dir <dir>]
  python3 scripts/gd-review-router.py --self-test

退出码（Plan 3a canonical — 3a-SC-4）：
  0 = APPROVED / route success
  1 = REQUIRES_CHANGES / routing decision non-APPROVED / validation failed
  2 = fail-closed missing input / usage error / side-door detection / no reviewable artifact

claude_review_origin field (Plan 3a — 3a-SC-2):
  skill_orchestrated  — Claude review generated by /gd command skill orchestration;
                         router is a consumer only; router does NOT spawn Claude subprocess.
  supplied            — Claude review JSON passed via --claude-review argument (direct CLI).
  not_applicable      — target kind does not use Claude review (execution_only, no_artifact).
"""
from __future__ import annotations

import argparse
import datetime
import json
import os
import subprocess
import sys
import uuid
from pathlib import Path


GD_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = GD_ROOT / "scripts"
FIXTURES_V2 = GD_ROOT / "fixtures" / "review-router-v2"
ROUTE_REPORT_VALIDATOR = SCRIPTS / "gd-validate-route-report.py"

# Plan 8 v4.1 Step 2: enums sourced from SSOT (gd_review_contract).
# Plan 8 v4.1 Step 5: classification logic shared with the detector via
# gd_review_detection — the router no longer maintains an independent matrix.
sys.path.insert(0, str(SCRIPTS))
from gd_review_contract import MODE_ENUM as VALID_MODES  # noqa: E402
from gd_review_contract import REVIEW_TARGET_KIND_ENUM as _VALID_KINDS  # noqa: E402
from gd_review_detection import (  # noqa: E402
    classify_artifacts,
    has_execution_artifacts_in_dir,
    is_execution_json,
)

# Q2 signature written into every route report
VALIDATOR_SIGNATURE = {
    "validator": "gd-validate-route-report.py",
    "schema_version": "2.0",
}

# Q3: env var set BY the router for scripts it spawns; must be absent on entry
INVOCATION_ID_ENV = "GD_REVIEW_ROUTER_INVOCATION_ID"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def err(code: str, msg: str, rc: int = 1) -> int:
    print(f"ERROR: {code}: {msg}", file=sys.stderr)
    return rc


def now_iso() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def generate_invocation_id() -> str:
    return f"router-{datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{uuid.uuid4().hex[:8]}"


def write_and_validate_route_report(report: dict, output_dir: Path) -> tuple[int, Path]:
    """Write route_report.json + validate via SSOT. Returns (rc, path)."""
    output_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    rp = output_dir / f"route_report_{ts}.json"
    rp.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    r = subprocess.run(
        [sys.executable, str(ROUTE_REPORT_VALIDATOR), str(rp)],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        print(f"ROUTE_REPORT_VALIDATION_FAIL: {r.stderr.strip()}", file=sys.stderr)
        return 1, rp
    print(f"ROUTE_REPORT: {rp}")
    print(f"ROUTE_REPORT_VALIDATION: OK")
    return 0, rp


DETECTOR_SCRIPT = SCRIPTS / "gd-detect-review-target.py"


def _is_router_descriptor(path: Path) -> bool:
    """Return True if a JSON file is a v1 router input descriptor (has router_version + artifacts)."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return "router_version" in data and "artifacts" in data
    except Exception:
        pass
    return False


def _classify_router_descriptor(path: Path) -> str:
    """Classify a v1 router-input descriptor via the shared SSOT helper.

    Mirrors gd-detect-review-target.detect_kind() so router/detector parity is
    preserved without a subprocess hop.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return "no_artifact"
    artifacts = (data or {}).get("artifacts", {}) if isinstance(data, dict) else {}
    if not isinstance(artifacts, dict):
        return "no_artifact"
    return classify_artifacts(
        bool(artifacts.get("plan_files")),
        bool(artifacts.get("execution_files")),
        bool(artifacts.get("code_diff")),
        bool(artifacts.get("bundle_declared", False)),
    )


def detect_review_target_kind(target: Path | None) -> str:
    """Target detection for detect_only / live_dry_run / live modes.

    Returns one of the REVIEW_TARGET_KIND_ENUM values. Plan 8 v4.1 Step 5
    delegates the artifact decision matrix to gd_review_detection.classify_artifacts
    so this function only handles file-system → (has_plan, has_exec, has_code)
    mapping. ``bundle_declared`` is treated as False for filesystem targets;
    explicit bundles must come through router-input JSON descriptors.
    """
    if target is None or not target.exists():
        return "no_artifact"

    if target.is_file():
        if target.suffix == ".md":
            return classify_artifacts(True, False, False)
        if target.suffix == ".json":
            # v1 router descriptor → use its declared artifacts.
            if _is_router_descriptor(target):
                return _classify_router_descriptor(target)
            # Raw execution artifact → content-based inspection.
            if is_execution_json(target):
                return classify_artifacts(False, True, False)
        return "no_artifact"

    if target.is_dir():
        has_plan = any(target.glob("**/*.md"))
        has_exec = has_execution_artifacts_in_dir(target)
        # Filesystem walks have no bundle marker → keep bundle_declared False.
        return classify_artifacts(has_plan, has_exec, False)

    return "no_artifact"


# ---------------------------------------------------------------------------
# Mode handlers
# ---------------------------------------------------------------------------

def run_fixture(fixture_path: Path, output_dir: Path, invocation_id: str) -> int:
    if not fixture_path.exists():
        return err("FIXTURE_NOT_FOUND", str(fixture_path))
    try:
        fx = json.loads(fixture_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return err("FIXTURE_INVALID_JSON", str(exc))

    meta = fx.get("_fixture_meta", {})
    expect = meta.get("_test_expect", "?")

    print(f"=== gd-review-router: fixture mode ===")
    print(f"fixture   : {fixture_path.name}")
    print(f"expect    : {expect}")
    print()

    # Build route report from fixture data (strip _fixture_meta before writing)
    report = {k: v for k, v in fx.items() if not k.startswith("_")}
    # Ensure required fields are present (router injects them if missing).
    report.setdefault("schema_version", "2.0")
    report["router_invocation_id"] = invocation_id
    # validator_signature: only inject for PASS fixtures. FAIL fixtures may intentionally
    # carry missing or wrong signatures to test schema validation rejection — don't fix them.
    if expect != "FAIL":
        report.setdefault("validator_signature", VALIDATOR_SIGNATURE)
    report.setdefault("recorded_at", now_iso())
    report.setdefault("findings", [])

    rc, rp = write_and_validate_route_report(report, output_dir)

    # For MUST FAIL fixtures: schema violation is expected
    if expect == "FAIL":
        if rc != 0:
            print(f"✓ fixture expects FAIL — route report schema violation (as expected)")
            return 0
        else:
            print(
                f"✗ fixture expects FAIL but route report passed schema validation — "
                f"this fixture should trigger a violation",
                file=sys.stderr,
            )
            return 1

    return rc


def run_detect_only(target: Path | None, output_dir: Path, invocation_id: str) -> int:
    print(f"=== gd-review-router: detect_only mode ===")
    print(f"target    : {target or '(auto)'}")
    print()

    kind = detect_review_target_kind(target)
    print(f"detected target kind: {kind}")

    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "detect_only",
        "review_target_kind": kind,
        "decision": "REVIEW_TARGET_MISSING" if kind == "no_artifact" else "REQUIRES_CHANGES",
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "findings": [],
        "notes": "detect_only: no review was invoked; detection result only",
    }

    rc, _ = write_and_validate_route_report(report, output_dir)
    return rc


def run_live_dry_run(target: Path | None, output_dir: Path, invocation_id: str) -> int:
    print(f"=== gd-review-router: live_dry_run mode ===")
    print(f"target    : {target or '(auto)'}")
    print()

    kind = detect_review_target_kind(target)
    print(f"detected target kind: {kind}")
    print(f"mock bridge: skipping Codex API call (live_dry_run)")

    # Simulate routing without actual review
    decision = "REVIEW_TARGET_MISSING" if kind == "no_artifact" else "REQUIRES_CHANGES"
    findings = []
    if kind != "no_artifact":
        findings.append({
            "reviewer": "router_mock",
            "severity": "info",
            "description": "live_dry_run: mock review result; no actual Codex bridge was called",
        })

    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live_dry_run",
        "review_target_kind": kind,
        "decision": decision,
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "findings": findings,
        "codex_transport_status": "not_called",
        "notes": "live_dry_run: Codex bridge was MOCKED — not a real review result",
    }

    rc, _ = write_and_validate_route_report(report, output_dir)
    return rc


def _run_live_plan_review(
    target: Path,
    output_dir: Path,
    invocation_id: str,
    claude_review: str | None,
    codex_raw_result: str | None,
    codex_mapped_result: str | None,
    review_contract: str,
    expected_target_hash: str | None,
) -> int:
    """Plan 1: invoke merge loop via subprocess for plan_only live review."""
    import hashlib, subprocess, tempfile

    # Compute plan_hash early so even fail-closed reports satisfy plan_only validator (plan_ref + plan_hash required).
    plan_hash = hashlib.sha256(target.read_bytes()).hexdigest()

    if not claude_review:
        print("ERROR: CLAUDE_REVIEW_REQUIRED: --claude-review is required for live plan review", file=sys.stderr)
        print("NOTE: In skill_orchestrated path (/gd review plan), Claude command generates", file=sys.stderr)
        print("      the review JSON automatically. Direct CLI calls must supply --claude-review.", file=sys.stderr)
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "plan_only",
            "decision": "FAILED",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "plan_ref": str(target),
            "plan_hash": plan_hash,
            "claude_review_origin": "skill_orchestrated",
            "findings": [{"reviewer": "router", "severity": "error",
                          "description": "CLAUDE_REVIEW_REQUIRED: no --claude-review supplied; "
                                         "expected via skill_orchestrated path or --claude-review CLI arg"}],
            "failure_code": "CLAUDE_REVIEW_REQUIRED",
        }
        write_and_validate_route_report(report, output_dir)
        return 2

    # Build merge loop argv
    loop_script = Path(__file__).parent / "gd-review-merge-and-fix-loop.py"
    cmd = [sys.executable, str(loop_script),
           "--plan", str(target),
           "--claude-review", claude_review,
           "--review-contract", review_contract,
           "--output-dir", str(output_dir),
           "--legacy-direct"]
    if codex_raw_result:
        cmd += ["--codex-raw-result", codex_raw_result]
    if codex_mapped_result:
        cmd += ["--codex-mapped-result", codex_mapped_result]
    if expected_target_hash:
        cmd += ["--expected-target-hash", expected_target_hash]

    env = {**os.environ, INVOCATION_ID_ENV: invocation_id}
    r = subprocess.run(cmd, capture_output=False, text=True, env=env)

    # Find loop report written by merge loop
    loop_reports = sorted(output_dir.glob("loop_report_*.json"))
    loop_report_path = str(loop_reports[-1]) if loop_reports else None
    downstream_decision = "FAILED"
    raw_result_path = None
    raw_result_hash = None

    if loop_report_path:
        try:
            lrep = json.loads(Path(loop_report_path).read_text(encoding="utf-8"))
            downstream_decision = lrep.get("gd_review_decision", "FAILED")
            raw_result_path = lrep.get("raw_result_path")
            rh = lrep.get("raw_result_hash")
            raw_result_hash = str(rh) if rh else None
        except Exception:
            pass

    # claude_review_origin: supplied if --claude-review was passed explicitly;
    # in skill_orchestrated path (/gd review plan), Claude command writes the JSON first.
    cr_origin = "supplied" if claude_review else "skill_orchestrated"
    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live",
        "review_target_kind": "plan_only",
        "decision": downstream_decision,
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "plan_ref": str(target),
        "plan_hash": plan_hash,
        "raw_result_path": raw_result_path,
        "raw_result_hash": raw_result_hash,
        "claude_review_origin": cr_origin,
        "downstream_loop_report_path": loop_report_path,
        "downstream_returncode": r.returncode,
        "findings": [],
    }
    write_and_validate_route_report(report, output_dir)
    return 0 if downstream_decision == "APPROVED" else 1


def _run_live_execution_only(
    target: Path,
    output_dir: Path,
    invocation_id: str,
    codex_raw_result: Path | None = None,
    codex_mapped_result: Path | None = None,
    review_contract: str = "auto",
) -> int:
    """execution_only_no_code (Execution-Review Cross-Review v2):
      Stage 1: invoke gd-validate-execution-outcome.py (validate facts/deliverables/verify-reruns)
      Stage 2: invoke / consume Codex bridge cross-review (validates review quality / SC / anti-fill)
      APPROVED requires BOTH stages pass; missing Codex → REQUIRES_CHANGES with codex_review_status.
    """
    import hashlib
    outcome_script = SCRIPTS / "gd-validate-execution-outcome.py"
    output_dir.mkdir(parents=True, exist_ok=True)

    # --- Stage 1: local outcome validator (validates facts) ---
    r_outcome = subprocess.run(
        [sys.executable, str(outcome_script), str(target)],
        capture_output=True, text=True,
        env={**os.environ, INVOCATION_ID_ENV: invocation_id},
    )
    exec_hash = hashlib.sha256(target.read_bytes()).hexdigest()

    if r_outcome.returncode != 0:
        # Outcome failed → Codex MUST NOT run; final REQUIRES_CHANGES.
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "execution_only_no_code",
            "decision": "REQUIRES_CHANGES",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "execution_artifact_ref": str(target),
            "execution_artifact_hash": exec_hash,
            "outcome_validator_status": "failed",
            "codex_review_status": "not_run_blocked",
            "codex_review_kind": "execution_outcome",
            "failure_code": "OUTCOME_VALIDATOR_FAIL",
            "claude_review_origin": "not_applicable",
            "findings": [{
                "reviewer": "outcome_validator",
                "severity": "error",
                "description": (r_outcome.stderr[:500] if r_outcome.stderr else "outcome validator failed"),
            }],
        }
        write_and_validate_route_report(report, output_dir)
        return 1

    # --- Stage 2: Codex bridge cross-review (validates review quality) ---
    bridge_script = SCRIPTS / "gd-codex-bridge-review.py"
    codex_status = "not_run_blocked"
    codex_decision = None
    codex_raw_path = None
    codex_raw_hash = None
    codex_mapped_path = None
    codex_mapped_hash = None
    findings: list = []

    # Path A: caller injected raw fixture → parse-transport (offline)
    if codex_raw_result is not None:
        mapped_out = output_dir / f"codex_mapped_{invocation_id[-8:]}.json"
        mapped_out = output_dir / f"codex_mapped_{invocation_id[-8:]}.json"
        parse_args = [
            sys.executable, str(bridge_script), "parse-transport",
            "--kind", "execution_outcome",
            "--target", str(target),
            "--raw-result", str(codex_raw_result),
            "--out", str(mapped_out),
        ]
        # revision=20: current Codex writer still outputs v1-style header
        # ("# Code Review Result") for execution kinds; always use --compat-v1
        # when parsing execution_outcome raw until writer migrates to v2 header.
        # Explicit "v2" contract overrides this to enforce v2 header strictly.
        if review_contract != "v2":
            parse_args.append("--compat-v1")
        r_bridge = subprocess.run(parse_args, capture_output=True, text=True)
        if r_bridge.returncode != 0:
            codex_status = "wrapper_schema_fail"
            findings.append({
                "reviewer": "codex_bridge",
                "severity": "error",
                "description": f"bridge parse-transport failed: {r_bridge.stderr[:400]}",
            })
        else:
            codex_status = "completed"
            codex_raw_path = str(codex_raw_result)
            codex_raw_hash = hashlib.sha256(codex_raw_result.read_bytes()).hexdigest()
            codex_mapped_path = str(mapped_out)
            codex_mapped_hash = hashlib.sha256(mapped_out.read_bytes()).hexdigest()
            try:
                mapped = json.loads(mapped_out.read_text(encoding="utf-8"))
                codex_decision = mapped.get("gd_review_decision") or mapped.get("decision")
                if codex_decision == "REQUIRES_CHANGES":
                    codex_status = "requires_changes"
                for f in mapped.get("findings", []) or []:
                    findings.append({**f, "reviewer": "codex"})
            except Exception as e:
                codex_status = "wrapper_schema_fail"
                findings.append({"reviewer": "codex_bridge", "severity": "error",
                                 "description": f"mapped JSON unreadable: {e}"})
    # Path B: caller injected mapped fixture → use directly
    elif codex_mapped_result is not None:
        try:
            mapped = json.loads(codex_mapped_result.read_text(encoding="utf-8"))
            codex_decision = mapped.get("gd_review_decision") or mapped.get("decision")
            codex_status = "requires_changes" if codex_decision == "REQUIRES_CHANGES" else "completed"
            codex_mapped_path = str(codex_mapped_result)
            codex_mapped_hash = hashlib.sha256(codex_mapped_result.read_bytes()).hexdigest()
            # raw_path unknown when only mapped supplied; mark synthetic
            codex_raw_path = str(codex_mapped_result) + ".raw_unknown"
            codex_raw_hash = "0" * 64
            for f in mapped.get("findings", []) or []:
                findings.append({**f, "reviewer": "codex"})
        except Exception as e:
            codex_status = "wrapper_schema_fail"
            findings.append({"reviewer": "codex_bridge", "severity": "error",
                             "description": f"mapped JSON unreadable: {e}"})
    # Path C: no injection → invoke bridge run-bridge --live-transport (revision=20 wired).
    # Codex writer still outputs v1 header; bridge then parse-transport --compat-v1 converts to mapped.
    else:
        run_out = output_dir / f"bridge_run_{invocation_id[-8:]}.log"
        run_args = [
            sys.executable, str(bridge_script), "run-bridge",
            "--kind", "execution_outcome",
            "--target", str(target),
            "--cwd", str(GD_ROOT),
            "--out", str(run_out),
            "--live-transport",
        ]
        try:
            r_run = subprocess.run(run_args, capture_output=True, text=True, timeout=120,
                                   env={**os.environ, INVOCATION_ID_ENV: invocation_id})
        except subprocess.TimeoutExpired:
            codex_status = "transport_failed"
            findings.append({"reviewer": "router", "severity": "error",
                             "description": "bridge run-bridge --live-transport timed out after 120s"})
            r_run = None
        if r_run is not None:
            # Extract TRANSPORT_RESULT from bridge stdout
            transport_raw = None
            for line in (r_run.stdout or "").splitlines():
                if line.startswith("TRANSPORT_RESULT: "):
                    transport_raw = Path(line[len("TRANSPORT_RESULT: "):].strip())
            if transport_raw is None or not transport_raw.exists():
                codex_status = "transport_failed"
                findings.append({"reviewer": "router", "severity": "error",
                                 "description": f"bridge run-bridge did not produce TRANSPORT_RESULT: {r_run.stdout[-300:]}"})
            else:
                # parse-transport --compat-v1 (Codex writer still uses v1 header for execution kinds)
                mapped_out = output_dir / f"codex_live_mapped_{invocation_id[-8:]}.json"
                parse_args = [
                    sys.executable, str(bridge_script), "parse-transport",
                    "--kind", "execution_outcome",
                    "--target", str(target),
                    "--raw-result", str(transport_raw),
                    "--out", str(mapped_out),
                    "--compat-v1",
                ]
                r_parse = subprocess.run(parse_args, capture_output=True, text=True)
                if r_parse.returncode != 0 or not mapped_out.exists():
                    codex_status = "wrapper_schema_fail"
                    findings.append({"reviewer": "codex_bridge", "severity": "error",
                                     "description": f"parse-transport failed: {r_parse.stderr[:300]}"})
                else:
                    try:
                        mapped = json.loads(mapped_out.read_text(encoding="utf-8"))
                        codex_decision = mapped.get("gd_review_decision") or mapped.get("decision")
                        codex_status = "completed" if codex_decision != "REQUIRES_CHANGES" else "requires_changes"
                        codex_raw_path = str(transport_raw)
                        codex_raw_hash = hashlib.sha256(transport_raw.read_bytes()).hexdigest()
                        codex_mapped_path = str(mapped_out)
                        codex_mapped_hash = hashlib.sha256(mapped_out.read_bytes()).hexdigest()
                        for f in mapped.get("findings", []) or []:
                            findings.append({**f, "reviewer": "codex"})
                    except Exception as e:
                        codex_status = "wrapper_schema_fail"
                        findings.append({"reviewer": "codex_bridge", "severity": "error",
                                         "description": f"mapped JSON unreadable: {e}"})

    # --- Decision merge: APPROVED requires outcome pass + Codex completed APPROVED ---
    if codex_status == "completed" and (codex_decision in (None, "APPROVED")):
        final_decision = "APPROVED"
    else:
        final_decision = "REQUIRES_CHANGES"

    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live",
        "review_target_kind": "execution_only_no_code",
        "decision": final_decision,
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "execution_artifact_ref": str(target),
        "execution_artifact_hash": exec_hash,
        "outcome_validator_status": "passed",
        "codex_review_kind": "execution_outcome",
        "codex_review_status": codex_status,
        "claude_review_origin": "not_applicable",
        "findings": findings,
    }
    if codex_raw_path is not None:
        report["codex_raw_result_path"] = codex_raw_path
        report["codex_raw_result_hash"] = codex_raw_hash
    if codex_mapped_path is not None:
        report["codex_mapped_result_path"] = codex_mapped_path
        report["codex_mapped_result_hash"] = codex_mapped_hash
    if codex_status == "transport_failed":
        report["failure_code"] = "CODEX_TRANSPORT_UNAVAILABLE"
    elif codex_status == "wrapper_schema_fail":
        report["failure_code"] = "CODEX_WRAPPER_SCHEMA_FAIL"

    write_and_validate_route_report(report, output_dir)
    return 0 if final_decision == "APPROVED" else 1


def _run_live_code_only(
    target: Path,
    output_dir: Path,
    invocation_id: str,
) -> int:
    """code_only: LOCAL_STATIC_ONLY — delegated to skill_orchestrated Claude (3a-SC-5/SC-9).
    Must not claim active/live Codex sidecar.
    handler = skill_orchestrated Claude static review
    allowed decisions = APPROVED | REQUIRES_CHANGES | FAILED (failure_code=LOCAL_STATIC_ONLY)
    Always exits 1 (REQUIRES_CHANGES) since actual review done by skill_orchestrated Claude."""
    import hashlib
    output_dir.mkdir(parents=True, exist_ok=True)
    # Compute diff for audit trail
    try:
        cwd = str(target.parent if target.is_file() else target)
        r_diff = subprocess.run(
            ["git", "diff", "HEAD", "--", str(target)],
            capture_output=True, text=True, cwd=cwd,
        )
        diff_content = r_diff.stdout if r_diff.stdout else f"# no diff output; git exit={r_diff.returncode}; target={target}"
    except Exception as e:
        diff_content = f"# git diff unavailable: {e}"
    diff_hash = hashlib.sha256(diff_content.encode()).hexdigest()
    diff_path = output_dir / f"code_diff_{invocation_id[-8:]}.patch"
    diff_path.write_text(diff_content, encoding="utf-8")
    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live",
        "review_target_kind": "code_only",
        "decision": "REQUIRES_CHANGES",
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "diff_source": f"git diff HEAD -- {target}",
        "diff_hash": diff_hash,
        "patch_generation_method": "git_diff",
        "raw_result_path": str(diff_path),
        "raw_result_hash": diff_hash,
        "claude_review_origin": "skill_orchestrated",
        "failure_code": "LOCAL_STATIC_ONLY",
        "findings": [{
            "reviewer": "router",
            "severity": "info",
            "description": (
                "code_only: static review delegated to skill_orchestrated Claude. "
                "Router records diff for audit trail; Codex code sidecar NOT active (3a-SC-9). "
                "REQUIRES_CHANGES until skill_orchestrated review completes."
            ),
        }],
    }
    # L3 content-evidence validation note (SC-W2-2):
    # code_only router does not have a real Codex review to validate at this stage.
    # The diff_path is the diff itself, not a review output. L3 would be a no-op
    # (target == review). The actual L3 gate runs in parse-transport when Codex
    # returns a real review result. No L3 call here prevents the no-op false pass.

    write_and_validate_route_report(report, output_dir)
    return 1  # REQUIRES_CHANGES — actual verdict from skill_orchestrated review


def _run_live_execution_plus_code(
    target: Path,
    output_dir: Path,
    invocation_id: str,
    codex_raw_result: Path | None = None,
    codex_mapped_result: Path | None = None,
    review_contract: str = "auto",
) -> int:
    """execution_plus_code: outcome-first, then code if passes (3a-SC-5/SC-7).
    Stage 1: gd-validate-execution-outcome.py
    Stage 2 (only if outcome passes): LOCAL_STATIC_ONLY code review (skill_orchestrated)"""
    import hashlib
    outcome_script = SCRIPTS / "gd-validate-execution-outcome.py"
    r_outcome = subprocess.run(
        [sys.executable, str(outcome_script), str(target)],
        capture_output=True, text=True,
        env={**os.environ, INVOCATION_ID_ENV: invocation_id},
    )
    raw_hash = hashlib.sha256(target.read_bytes()).hexdigest()

    if r_outcome.returncode != 0:
        # Outcome failed → OUTCOME_FIRST_FAIL; code review MUST NOT run (3a-SC-7)
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "execution_plus_code",
            "decision": "FAILED",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "execution_artifact_ref": str(target),
            "outcome_validator_status": "not_run_blocked",
            "stage_order": ["outcome", "code"],
            "failure_code": "OUTCOME_FIRST_FAIL",
            "claude_review_origin": "not_applicable",
            "findings": [{
                "reviewer": "outcome_validator",
                "severity": "error",
                "description": (
                    "outcome validation failed; code review BLOCKED per outcome-first rule (3a-SC-7). "
                    + (r_outcome.stderr[:400] if r_outcome.stderr else "")
                ),
            }],
        }
        write_and_validate_route_report(report, output_dir)
        return 1

    # Outcome passed → Stage 2: combined Codex cross-review (Execution-Review Cross-Review v2)
    output_dir.mkdir(parents=True, exist_ok=True)
    exec_hash = hashlib.sha256(target.read_bytes()).hexdigest()
    bridge_script = SCRIPTS / "gd-codex-bridge-review.py"
    codex_status = "not_run_blocked"
    codex_decision = None
    codex_raw_path = None
    codex_raw_hash = None
    codex_mapped_path = None
    codex_mapped_hash = None
    findings: list = []

    if codex_raw_result is not None:
        mapped_out = output_dir / f"codex_combined_mapped_{invocation_id[-8:]}.json"
        parse_args = [
            sys.executable, str(bridge_script), "parse-transport",
            "--kind", "combined",
            "--target", str(target),
            "--raw-result", str(codex_raw_result),
            "--out", str(mapped_out),
        ]
        # revision=20: same compat-v1 policy as execution_only path
        if review_contract != "v2":
            parse_args.append("--compat-v1")
        r_bridge = subprocess.run(parse_args, capture_output=True, text=True)
        if r_bridge.returncode != 0:
            codex_status = "wrapper_schema_fail"
            findings.append({"reviewer": "codex_bridge", "severity": "error",
                             "description": f"bridge parse-transport failed: {r_bridge.stderr[:400]}"})
        else:
            codex_status = "completed"
            codex_raw_path = str(codex_raw_result)
            codex_raw_hash = hashlib.sha256(codex_raw_result.read_bytes()).hexdigest()
            codex_mapped_path = str(mapped_out)
            codex_mapped_hash = hashlib.sha256(mapped_out.read_bytes()).hexdigest()
            try:
                mapped = json.loads(mapped_out.read_text(encoding="utf-8"))
                codex_decision = mapped.get("gd_review_decision") or mapped.get("decision")
                if codex_decision == "REQUIRES_CHANGES":
                    codex_status = "requires_changes"
                for f in mapped.get("findings", []) or []:
                    findings.append({**f, "reviewer": "codex"})
            except Exception as e:
                codex_status = "wrapper_schema_fail"
                findings.append({"reviewer": "codex_bridge", "severity": "error",
                                 "description": f"mapped JSON unreadable: {e}"})
    elif codex_mapped_result is not None:
        try:
            mapped = json.loads(codex_mapped_result.read_text(encoding="utf-8"))
            codex_decision = mapped.get("gd_review_decision") or mapped.get("decision")
            codex_status = "requires_changes" if codex_decision == "REQUIRES_CHANGES" else "completed"
            codex_mapped_path = str(codex_mapped_result)
            codex_mapped_hash = hashlib.sha256(codex_mapped_result.read_bytes()).hexdigest()
            codex_raw_path = str(codex_mapped_result) + ".raw_unknown"
            codex_raw_hash = "0" * 64
            for f in mapped.get("findings", []) or []:
                findings.append({**f, "reviewer": "codex"})
        except Exception as e:
            codex_status = "wrapper_schema_fail"
            findings.append({"reviewer": "codex_bridge", "severity": "error",
                             "description": f"mapped JSON unreadable: {e}"})
    else:
        codex_status = "transport_failed"
        findings.append({
            "reviewer": "router", "severity": "error",
            "description": (
                "execution_plus_code: Codex combined cross-review required for APPROVED but no "
                "--codex-raw-result / --codex-mapped-result supplied."
            ),
        })

    final_decision = "APPROVED" if (codex_status == "completed" and codex_decision in (None, "APPROVED")) else "REQUIRES_CHANGES"

    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live",
        "review_target_kind": "execution_plus_code",
        "decision": final_decision,
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "execution_artifact_ref": str(target),
        "execution_artifact_hash": exec_hash,
        "outcome_validator_status": "passed",
        "stage_order": ["outcome", "code"],
        "codex_review_kind": "combined",
        "codex_review_status": codex_status,
        "claude_review_origin": "not_applicable",
        "findings": findings,
    }
    if codex_raw_path is not None:
        report["codex_raw_result_path"] = codex_raw_path
        report["codex_raw_result_hash"] = codex_raw_hash
    if codex_mapped_path is not None:
        report["codex_mapped_result_path"] = codex_mapped_path
        report["codex_mapped_result_hash"] = codex_mapped_hash
    if codex_status == "transport_failed":
        report["failure_code"] = "CODEX_TRANSPORT_UNAVAILABLE"
    elif codex_status == "wrapper_schema_fail":
        report["failure_code"] = "CODEX_WRAPPER_SCHEMA_FAIL"
    write_and_validate_route_report(report, output_dir)
    return 0 if final_decision == "APPROVED" else 1


def run_live(
    target: Path | None,
    output_dir: Path,
    invocation_id: str,
    claude_review: str | None = None,
    codex_raw_result: str | None = None,
    codex_mapped_result: str | None = None,
    review_contract: str = 'auto',
    expected_target_hash: str | None = None,
) -> int:
    print(f"=== gd-review-router: live mode ===")
    print(f"target    : {target or '(auto)'}")
    print()

    kind = detect_review_target_kind(target)
    print(f"detected target kind: {kind}")

    if kind == "no_artifact":
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "no_artifact",
            "decision": "REVIEW_TARGET_MISSING",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "failure_code": "NO_ARTIFACT_DETECTED",
            "claude_review_origin": "not_applicable",
            "findings": [{"reviewer": "router", "severity": "error",
                          "description": "REVIEW_TARGET_MISSING: no reviewable artifact detected; "
                                         "fail-closed (3a-SC-6). Must not APPROVE."}],
        }
        write_and_validate_route_report(report, output_dir)
        print("ERROR: REVIEW_TARGET_MISSING: no reviewable artifact detected; fail-closed", file=sys.stderr)
        return 2  # exit 2 = missing input / no artifact (3a-SC-4/SC-6)

    # Plan 1: plan_only kind can be handled via subprocess merge loop with Claude + Codex inputs
    if kind == "plan_only" and target is not None:
        return _run_live_plan_review(
            target=target,
            output_dir=output_dir,
            invocation_id=invocation_id,
            claude_review=claude_review,
            codex_raw_result=codex_raw_result,
            codex_mapped_result=codex_mapped_result,
            review_contract=review_contract,
            expected_target_hash=expected_target_hash,
        )

    # Plan 3a: non-plan target kinds — all have defined live behavior (3a-SC-5).
    # No NOT_IMPLEMENTED. Handlers below.
    if kind == "execution_only_no_code" and target is not None:
        return _run_live_execution_only(
            target, output_dir, invocation_id,
            codex_raw_result=(Path(codex_raw_result) if codex_raw_result else None),
            codex_mapped_result=(Path(codex_mapped_result) if codex_mapped_result else None),
            review_contract=review_contract,
        )

    if kind == "code_only" and target is not None:
        return _run_live_code_only(target, output_dir, invocation_id)

    if kind == "execution_plus_code" and target is not None:
        return _run_live_execution_plus_code(
            target, output_dir, invocation_id,
            codex_raw_result=(Path(codex_raw_result) if codex_raw_result else None),
            codex_mapped_result=(Path(codex_mapped_result) if codex_mapped_result else None),
            review_contract=review_contract,
        )

    # Fallback: target is None for a non-plan kind — fail-closed.
    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live",
        "review_target_kind": kind,
        "decision": "FAILED",
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "failure_code": "TARGET_REQUIRED_FOR_KIND",
        "claude_review_origin": "not_applicable",
        "findings": [{"reviewer": "router", "severity": "error",
                      "description": f"live mode: --target required for kind={kind}"}],
    }
    if kind in ("execution_only_no_code", "execution_plus_code"):
        report["execution_artifact_ref"] = "(missing)"
        report["outcome_validator_status"] = "not_run_blocked"
    if kind == "execution_plus_code":
        report["stage_order"] = ["outcome", "code"]
    write_and_validate_route_report(report, output_dir)
    return 1


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

def run_self_test() -> int:
    errors: list[str] = []

    print("=== gd-review-router self-test ===")

    # 1. Route report validator exists
    if not ROUTE_REPORT_VALIDATOR.exists():
        errors.append(f"ROUTE_REPORT_VALIDATOR missing: {ROUTE_REPORT_VALIDATOR}")
    else:
        print(f"  route report validator present ✓")

    # 2. fixtures/review-router-v2/ exists and has content
    if not FIXTURES_V2.exists():
        errors.append(f"FIXTURES_V2 dir missing: {FIXTURES_V2}")
    else:
        v2_files = list(FIXTURES_V2.glob("*.json"))
        if not v2_files:
            errors.append(f"FIXTURES_V2 dir empty: {FIXTURES_V2}")
        else:
            print(f"  v2 fixtures: {len(v2_files)} files ✓")

    # 3. Q3 env check: INVOCATION_ID_ENV must be absent on entry
    if os.environ.get(INVOCATION_ID_ENV):
        errors.append(
            f"SIDE_DOOR_DETECTED: {INVOCATION_ID_ENV} is set; "
            "self-test should not be called from within a router run"
        )
    else:
        print(f"  Q3 side-door env absent ✓")

    # 4. Smoke: fixture mode with a known-good fixture
    good_fx = FIXTURES_V2 / "plan-only-approved.json"
    if good_fx.exists():
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            iid = generate_invocation_id()
            rc = run_fixture(good_fx, Path(td), iid)
        if rc == 0:
            print(f"  fixture smoke (plan-only-approved): PASS ✓")
        else:
            errors.append("fixture smoke (plan-only-approved) FAIL")
    else:
        errors.append(f"smoke fixture not found: {good_fx}")

    if errors:
        print("\nSELF_TEST FAIL:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1
    print("\nSELF_TEST: PASS")
    return 0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    # Q3: refuse if the invocation ID env is already set (side-door prevention)
    if os.environ.get(INVOCATION_ID_ENV):
        print(
            f"ERROR: SIDE_DOOR_DETECTED: {INVOCATION_ID_ENV}={os.environ[INVOCATION_ID_ENV]!r} "
            f"is set on entry — the router must not be called from within another router run. "
            f"Unset {INVOCATION_ID_ENV} before invoking directly.",
            file=sys.stderr,
        )
        return 2

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--mode", choices=sorted(VALID_MODES), help="Router execution mode (required unless --self-test)")
    p.add_argument("--fixture", help="Path to fixture JSON (required for --mode fixture)")
    p.add_argument("--target", help="Path to review target (plan file or directory)")
    p.add_argument("--output-dir", default=None, help="Directory to write route_report.json (default: GD_ROOT/reports/review-router/)")
    p.add_argument("--invocation-id", default=None, help="Optional router invocation ID (auto-generated if absent)")
    p.add_argument("--self-test", action="store_true", help="Run self-test and exit")
    p.add_argument("--claude-review", default=None, metavar="CLAUDE_JSON",
                   help="(live plan mode) Path to Claude review mapped JSON.")
    p.add_argument("--codex-raw-result", default=None, metavar="RAW_MD",
                   help="(live plan mode) Path to existing Codex raw .result file (read-only).")
    p.add_argument("--codex-mapped-result", default=None, metavar="MAPPED_JSON",
                   help="(live plan mode) Path to pre-mapped Codex result JSON.")
    p.add_argument("--review-contract", default="auto", choices=["auto", "v1", "v2"],
                   help="Raw result parse contract for --codex-raw-result (default: auto).")
    p.add_argument("--expected-target-hash", default=None, metavar="HASH",
                   help="SHA-256 of plan at review submit time for binding check.")
    args = p.parse_args()

    if args.self_test:
        return run_self_test()

    if not args.mode:
        p.print_help()
        return 2

    invocation_id = args.invocation_id or generate_invocation_id()
    output_dir = Path(args.output_dir) if args.output_dir else GD_ROOT / "reports" / "review-router"
    target = Path(args.target) if args.target else None

    # Set invocation ID for downstream scripts (Q3: they can verify they're called from router)
    os.environ[INVOCATION_ID_ENV] = invocation_id

    if args.mode == "fixture":
        if not args.fixture:
            return err("FIXTURE_REQUIRED", "--fixture <path> is required for --mode fixture", 2)
        return run_fixture(Path(args.fixture), output_dir, invocation_id)
    elif args.mode == "detect_only":
        return run_detect_only(target, output_dir, invocation_id)
    elif args.mode == "live_dry_run":
        return run_live_dry_run(target, output_dir, invocation_id)
    elif args.mode == "live":
        return run_live(
            target, output_dir, invocation_id,
            claude_review=getattr(args, "claude_review", None),
            codex_raw_result=getattr(args, "codex_raw_result", None),
            codex_mapped_result=getattr(args, "codex_mapped_result", None),
            review_contract=getattr(args, "review_contract", "auto"),
            expected_target_hash=getattr(args, "expected_target_hash", None),
        )

    return err("UNKNOWN_MODE", args.mode, 2)


if __name__ == "__main__":
    sys.exit(main())
