#!/usr/bin/env python3
"""
gd-review-router.py — Plan 5 v3 Wave B

Unified /gd review state machine router.

Modes (--mode, required):
  fixture       Replay a pre-recorded fixture from fixtures/review-router-v2/.
  detect_only   Real target detection; no review invoked; writes route report.
  live_dry_run  Real detection + mock bridge wrapper; writes route report with mock flag.
  live          Full production run (requires Codex bridge available).

Route report:
  After every run the router writes a route_report.json and immediately validates
  it via scripts/gd-validate-route-report.py (SSOT). Consumers must verify
  validator_signature before trusting the report (Q2).

Q3 side-door prevention:
  The env var GD_REVIEW_ROUTER_INVOCATION_ID must NOT be set when invoking the router
  directly (it is only set BY the router for downstream scripts it spawns). A non-empty
  env value on entry signals an attempted side-door bypass and causes exit 2.

CLI:
  python3 scripts/gd-review-router.py --mode fixture --fixture <path.json> [--output-dir <dir>]
  python3 scripts/gd-review-router.py --mode detect_only [--target <path>] [--output-dir <dir>]
  python3 scripts/gd-review-router.py --mode live_dry_run [--target <path>] [--output-dir <dir>]
  python3 scripts/gd-review-router.py --mode live [--target <path>] [--output-dir <dir>]
  python3 scripts/gd-review-router.py --self-test

退出码（Plan 3a canonical — 3a-SC-4）：
  0 = APPROVED / route success
  1 = REQUIRES_CHANGES / routing decision non-APPROVED / validation failed
  2 = fail-closed missing input / usage error / side-door detection / no reviewable artifact

claude_review_origin field (Plan 3a — 3a-SC-2):
  skill_orchestrated  — Claude review generated by /gd command skill orchestration;
                         router is a consumer only; router does NOT spawn Claude subprocess.
  supplied            — Claude review JSON passed via --claude-review argument (direct CLI).
  not_applicable      — target kind does not use Claude review (execution_only, no_artifact).
"""
from __future__ import annotations

import argparse
import datetime
import json
import os
import subprocess
import sys
import uuid
from pathlib import Path


GD_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = GD_ROOT / "scripts"
FIXTURES_V2 = GD_ROOT / "fixtures" / "review-router-v2"
ROUTE_REPORT_VALIDATOR = SCRIPTS / "gd-validate-route-report.py"

# Plan 8 v4.1 Step 2: enums sourced from SSOT (gd_review_contract).
# Plan 8 v4.1 Step 5: classification logic shared with the detector via
# gd_review_detection — the router no longer maintains an independent matrix.
sys.path.insert(0, str(SCRIPTS))
from gd_review_contract import MODE_ENUM as VALID_MODES  # noqa: E402
from gd_review_contract import REVIEW_TARGET_KIND_ENUM as _VALID_KINDS  # noqa: E402
from gd_review_contract import codex_review_status_from_evidence  # noqa: E402
from gd_review_detection import (  # noqa: E402
    classify_artifacts,
    has_execution_artifacts_in_dir,
    is_execution_json,
)

# Q2 signature written into every route report
VALIDATOR_SIGNATURE = {
    "validator": "gd-validate-route-report.py",
    "schema_version": "2.0",
}

# Q3: env var set BY the router for scripts it spawns; must be absent on entry
INVOCATION_ID_ENV = "GD_REVIEW_ROUTER_INVOCATION_ID"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def err(code: str, msg: str, rc: int = 1) -> int:
    print(f"ERROR: {code}: {msg}", file=sys.stderr)
    return rc


def now_iso() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def generate_invocation_id() -> str:
    return f"router-{datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{uuid.uuid4().hex[:8]}"


def _write_route_report(report: dict, output_dir: Path) -> Path:
    """Write route_report.json to a timestamped path and return it (no validation)."""
    output_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    rp = output_dir / f"route_report_{ts}.json"
    rp.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return rp


def _validate_route_report_file(rp: Path) -> int:
    """Validate an already-written route report via SSOT. Returns rc (0 = ok)."""
    r = subprocess.run(
        [sys.executable, str(ROUTE_REPORT_VALIDATOR), str(rp)],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        print(f"ROUTE_REPORT_VALIDATION_FAIL: {r.stderr.strip()}", file=sys.stderr)
        return 1
    print(f"ROUTE_REPORT: {rp}")
    print(f"ROUTE_REPORT_VALIDATION: OK")
    return 0


def write_and_validate_route_report(
    report: dict, output_dir: Path, ledger_writer=None
) -> tuple[int, Path]:
    """Write route_report.json, optionally write its child ledger, then validate.

    Returns (rc, path).

    The route-report validator requires any referenced ``child_review_ledger_path``
    to exist on disk. Callers that populate ``report['child_review_ledger_path']``
    MUST pass a ``ledger_writer(rp)`` callback: it runs between the report write and
    validation, so the write -> ledger -> validate ordering lives here in one place
    and cannot be gotten wrong by individual call sites.
    """
    rp = _write_route_report(report, output_dir)
    if ledger_writer is not None:
        ledger_writer(rp)
    rc = _validate_route_report_file(rp)
    return rc, rp


DETECTOR_SCRIPT = SCRIPTS / "gd-detect-review-target.py"


def _is_router_descriptor(path: Path) -> bool:
    """Return True if a JSON file is a v1 router input descriptor (has router_version + artifacts)."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return "router_version" in data and "artifacts" in data
    except Exception:
        pass
    return False


# P2 sentinel: a JSON target that declared itself a router descriptor
# (router_version + artifacts keys present) but is unreadable/malformed at
# classification time. This is DISTINCT from a genuinely empty target
# ("no_artifact"): a corrupt descriptor means the caller intended to point at
# artifacts but the descriptor itself is broken — we surface a different
# failure_code so it is not silently bucketed as "nothing to review".
CORRUPT_DESCRIPTOR_SENTINEL = "corrupt_descriptor"


def _classify_router_descriptor(path: Path) -> str:
    """Classify a v1 router-input descriptor via the shared SSOT helper.

    Mirrors gd-detect-review-target.detect_kind() so router/detector parity is
    preserved without a subprocess hop. Returns CORRUPT_DESCRIPTOR_SENTINEL when
    a self-declared descriptor cannot be parsed/validated (P2 fail-closed),
    which the caller maps to a CORRUPT_ROUTER_DESCRIPTOR failure_code rather than
    NO_ARTIFACT_DETECTED.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return CORRUPT_DESCRIPTOR_SENTINEL
    artifacts = (data or {}).get("artifacts", {}) if isinstance(data, dict) else {}
    if not isinstance(artifacts, dict):
        return CORRUPT_DESCRIPTOR_SENTINEL
    return classify_artifacts(
        bool(artifacts.get("plan_files")),
        bool(artifacts.get("execution_files")),
        bool(artifacts.get("code_diff")),
        bool(artifacts.get("bundle_declared", False)),
    )


def detect_review_target_kind(target: Path | None) -> str:
    """Target detection for detect_only / live_dry_run / live modes.

    Returns one of the REVIEW_TARGET_KIND_ENUM values. Plan 8 v4.1 Step 5
    delegates the artifact decision matrix to gd_review_detection.classify_artifacts
    so this function only handles file-system → (has_plan, has_exec, has_code)
    mapping. ``bundle_declared`` is treated as False for filesystem targets;
    explicit bundles must come through router-input JSON descriptors.
    """
    if target is None or not target.exists():
        return "no_artifact"

    if target.is_file():
        if target.suffix == ".md":
            return classify_artifacts(True, False, False)
        if target.suffix == ".json":
            # v1 router descriptor → use its declared artifacts.
            if _is_router_descriptor(target):
                return _classify_router_descriptor(target)
            # Raw execution artifact → content-based inspection.
            if is_execution_json(target):
                return classify_artifacts(False, True, False)
        return "no_artifact"

    if target.is_dir():
        has_plan = any(target.glob("**/*.md"))
        has_exec = has_execution_artifacts_in_dir(target)
        # Filesystem walks have no bundle marker → keep bundle_declared False.
        return classify_artifacts(has_plan, has_exec, False)

    return "no_artifact"


# ---------------------------------------------------------------------------
# Mode handlers
# ---------------------------------------------------------------------------

def run_fixture(fixture_path: Path, output_dir: Path, invocation_id: str) -> int:
    if not fixture_path.exists():
        return err("FIXTURE_NOT_FOUND", str(fixture_path))
    try:
        fx = json.loads(fixture_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return err("FIXTURE_INVALID_JSON", str(exc))

    meta = fx.get("_fixture_meta", {})
    expect = meta.get("_test_expect", "?")

    print(f"=== gd-review-router: fixture mode ===")
    print(f"fixture   : {fixture_path.name}")
    print(f"expect    : {expect}")
    print()

    # Build route report from fixture data (strip _fixture_meta before writing)
    report = {k: v for k, v in fx.items() if not k.startswith("_")}
    # Ensure required fields are present (router injects them if missing).
    report.setdefault("schema_version", "2.0")
    report["router_invocation_id"] = invocation_id
    # validator_signature: only inject for PASS fixtures. FAIL fixtures may intentionally
    # carry missing or wrong signatures to test schema validation rejection — don't fix them.
    if expect != "FAIL":
        report.setdefault("validator_signature", VALIDATOR_SIGNATURE)
    report.setdefault("recorded_at", now_iso())
    report.setdefault("findings", [])

    rc, rp = write_and_validate_route_report(report, output_dir)

    # For MUST FAIL fixtures: schema violation is expected
    if expect == "FAIL":
        if rc != 0:
            print(f"✓ fixture expects FAIL — route report schema violation (as expected)")
            return 0
        else:
            print(
                f"✗ fixture expects FAIL but route report passed schema validation — "
                f"this fixture should trigger a violation",
                file=sys.stderr,
            )
            return 1

    return rc


def run_detect_only(target: Path | None, output_dir: Path, invocation_id: str) -> int:
    print(f"=== gd-review-router: detect_only mode ===")
    print(f"target    : {target or '(auto)'}")
    print()

    kind = detect_review_target_kind(target)
    print(f"detected target kind: {kind}")

    # P2: keep the report's review_target_kind enum-valid; a corrupt descriptor
    # is surfaced via the note + REVIEW_TARGET_MISSING decision, not APPROVE.
    is_corrupt = kind == CORRUPT_DESCRIPTOR_SENTINEL
    report_kind = "no_artifact" if is_corrupt else kind
    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "detect_only",
        "review_target_kind": report_kind,
        "decision": "REVIEW_TARGET_MISSING" if report_kind == "no_artifact" else "REQUIRES_CHANGES",
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "findings": [],
        "notes": (
            "detect_only: corrupt router descriptor (CORRUPT_ROUTER_DESCRIPTOR); fail-closed"
            if is_corrupt else
            "detect_only: no review was invoked; detection result only"
        ),
    }

    rc, _ = write_and_validate_route_report(report, output_dir)
    return rc


def run_live_dry_run(target: Path | None, output_dir: Path, invocation_id: str) -> int:
    print(f"=== gd-review-router: live_dry_run mode ===")
    print(f"target    : {target or '(auto)'}")
    print()

    kind = detect_review_target_kind(target)
    print(f"detected target kind: {kind}")
    print(f"mock bridge: skipping Codex API call (live_dry_run)")

    # P2: normalize corrupt-descriptor sentinel to an enum-valid kind for the
    # report while still fail-closing (REVIEW_TARGET_MISSING, never APPROVE).
    is_corrupt = kind == CORRUPT_DESCRIPTOR_SENTINEL
    report_kind = "no_artifact" if is_corrupt else kind

    # Simulate routing without actual review
    decision = "REVIEW_TARGET_MISSING" if report_kind == "no_artifact" else "REQUIRES_CHANGES"
    findings = []
    if report_kind != "no_artifact":
        findings.append({
            "reviewer": "router_mock",
            "severity": "info",
            "description": "live_dry_run: mock review result; no actual Codex bridge was called",
        })

    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live_dry_run",
        "review_target_kind": report_kind,
        "decision": decision,
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "findings": findings,
        "codex_transport_status": "not_called",
        "notes": "live_dry_run: Codex bridge was MOCKED — not a real review result",
    }

    rc, _ = write_and_validate_route_report(report, output_dir)
    return rc


def _run_live_plan_review(
    target: Path,
    output_dir: Path,
    invocation_id: str,
    claude_review: str | None,
    codex_raw_result: str | None,
    codex_mapped_result: str | None,
    review_contract: str,
    expected_target_hash: str | None,
) -> int:
    """Plan 1: invoke merge loop via subprocess for plan_only live review."""
    import hashlib, subprocess, tempfile

    # Compute plan_hash early so even fail-closed reports satisfy plan_only validator (plan_ref + plan_hash required).
    plan_hash = hashlib.sha256(target.read_bytes()).hexdigest()

    if not claude_review:
        print("ERROR: CLAUDE_REVIEW_REQUIRED: --claude-review is required for live plan review", file=sys.stderr)
        print("NOTE: In skill_orchestrated path (/gd review plan), Claude command generates", file=sys.stderr)
        print("      the review JSON automatically. Direct CLI calls must supply --claude-review.", file=sys.stderr)
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "plan_only",
            "decision": "FAILED",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "plan_ref": str(target),
            "plan_hash": plan_hash,
            "claude_review_origin": "skill_orchestrated",
            "findings": [{"reviewer": "router", "severity": "error",
                          "description": "CLAUDE_REVIEW_REQUIRED: no --claude-review supplied; "
                                         "expected via skill_orchestrated path or --claude-review CLI arg"}],
            "failure_code": "CLAUDE_REVIEW_REQUIRED",
        }
        write_and_validate_route_report(report, output_dir)
        return 2

    # Build merge loop argv
    loop_script = Path(__file__).parent / "gd-review-merge-and-fix-loop.py"
    cmd = [sys.executable, str(loop_script),
           "--plan", str(target),
           "--claude-review", claude_review,
           "--review-contract", review_contract,
           "--output-dir", str(output_dir),
           "--legacy-direct"]
    if codex_raw_result:
        cmd += ["--codex-raw-result", codex_raw_result]
    if codex_mapped_result:
        cmd += ["--codex-mapped-result", codex_mapped_result]
    if expected_target_hash:
        cmd += ["--expected-target-hash", expected_target_hash]

    env = {**os.environ, INVOCATION_ID_ENV: invocation_id}
    r = subprocess.run(cmd, capture_output=False, text=True, env=env)

    # Find loop report written by merge loop
    loop_reports = sorted(output_dir.glob("loop_report_*.json"))
    loop_report_path = str(loop_reports[-1]) if loop_reports else None
    downstream_decision = "FAILED"
    raw_result_path = None
    raw_result_hash = None
    codex_review_status = None  # read directly from loop_report (merge-loop computes it)

    if loop_report_path:
        try:
            lrep = json.loads(Path(loop_report_path).read_text(encoding="utf-8"))
            downstream_decision = lrep.get("gd_review_decision", "FAILED")
            raw_result_path = lrep.get("raw_result_path")
            rh = lrep.get("raw_result_hash")
            raw_result_hash = str(rh) if rh else None
            codex_review_status = lrep.get("codex_review_status")
        except Exception as exc:
            # Fail-visible (rule 12): a loop_report that EXISTS but won't parse is a
            # merge-loop writer bug, NOT a transport failure. Surface it on stderr so
            # codex-chain diagnosis isn't misdirected to transport/launchd/key.
            # Conservative transport_failed default still applied below.
            print(f"WARN: loop_report unreadable ({loop_report_path}): {exc}", file=sys.stderr)

    # Fail-closed: loop_report missing/unreadable or no codex_review_status field →
    # transport_failed. (The mapping logic lives in merge-loop, which has the
    # evidence triple; router only transports the computed value + defaults when
    # evidence is absent.)
    if not codex_review_status:
        codex_review_status = "transport_failed"
    if downstream_decision == "APPROVED":
        if codex_review_status == "transport_failed":
            downstream_decision = "FAILED"
        elif codex_review_status in ("wrapper_schema_fail", "requires_changes"):
            downstream_decision = "REQUIRES_CHANGES"

    # N4 fail-closed: the merge loop's exit code is authoritative. A non-zero
    # returncode means the loop did not cleanly converge to APPROVED, so we must
    # NOT trust an APPROVED read out of a possibly stale/partial loop_report.
    # (Bridge G6 arbitration: returncode beats decision.)
    if r.returncode != 0 and downstream_decision == "APPROVED":
        downstream_decision = "FAILED"

    # claude_review_origin: supplied if --claude-review was passed explicitly;
    # in skill_orchestrated path (/gd review plan), Claude command writes the JSON first.
    cr_origin = "supplied" if claude_review else "skill_orchestrated"
    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live",
        "review_target_kind": "plan_only",
        "decision": downstream_decision,
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "plan_ref": str(target),
        "plan_hash": plan_hash,
        "raw_result_path": raw_result_path,
        "raw_result_hash": raw_result_hash,
        "claude_review_origin": cr_origin,
        "downstream_loop_report_path": loop_report_path,
        "downstream_returncode": r.returncode,
        "codex_review_status": codex_review_status,
        "findings": [],
    }
    # Codex evidence: the loop_report's raw_result_path IS the codex mapped result
    # (bridge-r{round}-{lens}-mapped.json written by _run_bridge_job in merge-loop).
    # Mirror it into codex_* fields so plan review has the same observability as
    # the execution path (:1088-1093). Filled only when codex actually ran (non-None).
    if raw_result_path is not None:
        report["codex_mapped_result_path"] = raw_result_path
        report["codex_mapped_result_hash"] = raw_result_hash
    # Mirror execution path (:1094-1097): surface transport + wrapper failures with
    # explicit failure_codes so closure-eligibility scanners see them.
    if codex_review_status == "transport_failed":
        report["failure_code"] = "CODEX_TRANSPORT_UNAVAILABLE"
    elif codex_review_status == "wrapper_schema_fail":
        report["failure_code"] = "CODEX_WRAPPER_SCHEMA_FAIL"
    rc, _ = write_and_validate_route_report(report, output_dir)
    if rc != 0:
        return 1
    return 0 if downstream_decision == "APPROVED" else 1


def _run_live_codex_bridge(
    kind: str,
    target: Path,
    output_dir: Path,
    invocation_id: str,
    timeout_sec: int,
    deep: bool = False,
    plan_file: str | None = None,
) -> dict:
    """C2 helper: invoke Codex live bridge for execution_outcome or combined kind.

    Calls gd-codex-bridge-review.py run-bridge --live-transport with the given kind,
    then parse-transport --compat-v1 to map raw to mapped JSON.

    Returns:
      {
        "status": "completed" | "requires_changes" | "wrapper_schema_fail" | "transport_failed",
        "decision": "APPROVED" | "REQUIRES_CHANGES" | None,
        "raw_path": str | None,
        "raw_hash": str | None,
        "mapped_path": str | None,
        "mapped_hash": str | None,
        "findings": list,
        "failure_description": str | None,
      }

    Always sets GD_REVIEW_ROUTER_INVOCATION_ID env so bridge G1 sentinel allows.
    Honors --live-bridge-timeout-sec (default 360s); on timeout returns transport_failed.
    """
    import hashlib
    bridge_script = SCRIPTS / "gd-codex-bridge-review.py"
    output_dir.mkdir(parents=True, exist_ok=True)
    run_out = output_dir / f"bridge_run_{kind}_{invocation_id[-8:]}.log"

    result: dict = {
        "status": "transport_failed",
        "decision": None,
        "raw_path": None,
        "raw_hash": None,
        "mapped_path": None,
        "mapped_hash": None,
        "findings": [],
        "failure_description": None,
    }

    # SC-31: deep path requires bridge timeout ≥1800s
    if deep:
        timeout_sec = max(timeout_sec, 1800)

    run_args = [
        sys.executable, str(bridge_script), "run-bridge",
        "--kind", kind,
        "--target", str(target),
        "--cwd", str(GD_ROOT),
        "--out", str(run_out),
        "--live-transport",
    ]
    if deep:
        run_args.append("--deep")
    if plan_file:
        run_args += ["--plan-file", plan_file]
    try:
        r_run = subprocess.run(
            run_args, capture_output=True, text=True, timeout=timeout_sec,
            env={**os.environ, INVOCATION_ID_ENV: invocation_id},
        )
    except subprocess.TimeoutExpired:
        msg = f"bridge run-bridge --live-transport timed out after {timeout_sec}s"
        result["failure_description"] = msg
        result["findings"].append({"reviewer": "router", "severity": "error", "description": msg})
        return result

    transport_raw = None
    for line in (r_run.stdout or "").splitlines():
        if line.startswith("TRANSPORT_RESULT: "):
            transport_raw = Path(line[len("TRANSPORT_RESULT: "):].strip())
    if transport_raw is None or not transport_raw.exists():
        msg = f"bridge run-bridge did not produce TRANSPORT_RESULT: {(r_run.stdout or '')[-300:]}"
        result["failure_description"] = msg
        result["findings"].append({"reviewer": "router", "severity": "error", "description": msg})
        return result

    mapped_out = output_dir / f"codex_live_mapped_{kind}_{invocation_id[-8:]}.json"
    parse_args = [
        sys.executable, str(bridge_script), "parse-transport",
        "--kind", kind,
        "--target", str(target),
        "--raw-result", str(transport_raw),
        "--out", str(mapped_out),
    ]
    # G2 (bridge): parse-transport auto-infers --compat-v1 for execution_outcome/combined
    # when flag is omitted. Explicit flag here would also work; omit to keep helper simple.
    if deep:
        parse_args.append("--deep")
    r_parse = subprocess.run(parse_args, capture_output=True, text=True)
    # parse-transport returns non-zero for valid non-APPROVED mapped results.
    # Treat absence/unreadability of the mapped JSON as parse failure; otherwise
    # let codex_review_status_from_evidence classify the mapped decision.
    if not mapped_out.exists():
        msg = f"parse-transport failed: {(r_parse.stderr or '')[:300]}"
        result["status"] = "wrapper_schema_fail"
        result["failure_description"] = msg
        result["findings"].append({"reviewer": "codex_bridge", "severity": "error", "description": msg})
        return result

    try:
        mapped = json.loads(mapped_out.read_text(encoding="utf-8"))
    except Exception as e:
        msg = f"mapped JSON unreadable: {e}"
        result["status"] = "wrapper_schema_fail"
        result["failure_description"] = msg
        result["findings"].append({"reviewer": "codex_bridge", "severity": "error", "description": msg})
        return result

    decision = mapped.get("gd_review_decision") or mapped.get("decision")
    norm = str(decision).strip().upper() if decision is not None else "FAILED"
    status = codex_review_status_from_evidence(True, norm, mapped.get("review_run_status"))
    result["status"] = status
    if status == "completed":
        result["decision"] = "APPROVED"
    elif status == "requires_changes":
        result["decision"] = "REQUIRES_CHANGES"
    else:
        # FAILED, None, unknown verdict, or degraded/failed run status → fail-closed.
        result["decision"] = "FAILED"
        result["failure_description"] = (
            f"codex mapped evidence not a clean verdict "
            f"(decision={decision!r}, run_status={mapped.get('review_run_status')!r}); "
            "fail-closed to FAILED"
        )
        result["findings"].append({
            "reviewer": "codex_bridge", "severity": "error",
            "description": result["failure_description"],
        })
    result["raw_path"] = str(transport_raw)
    result["raw_hash"] = hashlib.sha256(transport_raw.read_bytes()).hexdigest()
    result["mapped_path"] = str(mapped_out)
    result["mapped_hash"] = hashlib.sha256(mapped_out.read_bytes()).hexdigest()
    for f in mapped.get("findings", []) or []:
        result["findings"].append({**f, "reviewer": "codex"})
    return result


def _write_execution_review_ledger(
    ledger_path: "Path",
    invocation_id: str,
    stage: str,
    codex_review_kind: str,
    outcome_validator_status: str,
    exec_hash: str,
    target: "Path",
    codex_status: str,
    codex_decision: "str | None",
    codex_mapped_path: "str | None",
    codex_mapped_hash: "str | None",
    codex_raw_path: "str | None",
    codex_raw_hash: "str | None",
    route_report_path: "Path",
    final_decision: str,
) -> None:
    """D1: Write child review ledger for execution review (outcome_validator + Codex bridge).

    Ledger aligns with schema/gd-stage-dispatch-ledger.schema.json.
    stage='review_execution_code' (enum value from stage-dispatch-ledger schema).
    child_agent_count=2: outcome validator + Codex bridge cross-review.
    """
    import hashlib
    merge_hash = hashlib.sha256(route_report_path.read_bytes()).hexdigest() if route_report_path.exists() else ("0" * 64)
    ledger = {
        "schema_version": "1.0",
        "stage": stage,
        "parent_run_id": invocation_id,
        "recorded_at": now_iso(),
        "child_agent_count": 2,
        "max_parallel": 2,
        "child_jobs": [
            {
                "job_id": f"{invocation_id[-8:]}-outcome",
                "result_path": str(target),
                "result_hash": exec_hash,
                "status": "completed" if outcome_validator_status == "passed" else "failed",
            },
            {
                "job_id": f"{invocation_id[-8:]}-codex-{codex_review_kind}",
                "result_path": codex_mapped_path or "",
                "result_hash": codex_mapped_hash or ("0" * 64),
                "status": codex_status,
            },
        ],
        "main_agent_merge": {
            "merge_report_path": str(route_report_path),
            "merge_report_hash": merge_hash,
            "final_decision": final_decision,
        },
    }
    ledger_path.parent.mkdir(parents=True, exist_ok=True)
    ledger_path.write_text(json.dumps(ledger, ensure_ascii=False, indent=2), encoding="utf-8")


CONTROLLER_SCRIPT = SCRIPTS / "gd-review-controller.py"


def _run_controller_multi_round(
    branch: str,
    target: Path,
    output_dir: Path,
    invocation_id: str,
    execution_result: Path | None = None,
    claude_review_json: Path | None = None,
    round2_fanout_threshold_lines: int = 150,
    round2_fanout_threshold_files: int = 5,
    max_rounds: int = 10,
    deep: bool = False,
    plan_file: str | None = None,
) -> int:
    """T7: Invoke gd-review-controller.py as the multi-round loop driver for
    execution_outcome and combined routes.

    The controller runs Branch B (execution-only) or Branch C (combined) in a
    convergence loop, emitting CONVERGENCE_TIMEOUT on stagnation or APPROVED on
    success. This function is the router's integration point for T7 controller.

    Returns 0 on APPROVED, 1 on CONVERGENCE_TIMEOUT / REQUIRES_CHANGES, 2 on error.
    """
    if not CONTROLLER_SCRIPT.exists():
        print(
            f"ERROR: CONTROLLER_NOT_FOUND: {CONTROLLER_SCRIPT} — T7 controller not deployed",
            file=sys.stderr,
        )
        return 2

    cmd = [
        sys.executable, str(CONTROLLER_SCRIPT),
        "--branch", branch,
        "--cwd", str(GD_ROOT),
        "--output-dir", str(output_dir),
        f"--round2-fanout-threshold-lines={round2_fanout_threshold_lines}",
        f"--round2-fanout-threshold-files={round2_fanout_threshold_files}",
        f"--max-rounds={max_rounds}",
    ]
    if execution_result is not None:
        cmd += ["--execution-result", str(execution_result)]
    if claude_review_json is not None:
        cmd += ["--claude-review-json", str(claude_review_json)]
    if deep:
        cmd.append("--deep")
    if plan_file:
        cmd += ["--plan-file", plan_file]

    env = {**os.environ, INVOCATION_ID_ENV: invocation_id}
    r = subprocess.run(cmd, capture_output=False, text=True, env=env)
    return r.returncode


def _run_upstream_quality_gate(target: "Path", output_dir: "Path", invocation_id: str) -> dict:
    """Run /code-review + /simplify upstream quality gate.

    Returns dict:
      {
        "steps": [
          {"step": "code-review", "status": "ok"|"unavailable"|"failed",
           "exit_code": int, "output_ref": str, "output_hash": str},
          {"step": "simplify", ...},
        ],
        "failure_code": str | None,  # UPSTREAM_QUALITY_GATE_FAIL / CODE_REVIEW_UNAVAILABLE / SIMPLIFY_UNAVAILABLE
        "fail_closed": bool,
      }

    fail-closed contract (SC-1 / master SC-5):
      - tool unavailable → fail_closed=True, failure_code=<TOOL>_UNAVAILABLE
      - tool exits non-zero → fail_closed=True, failure_code=UPSTREAM_QUALITY_GATE_FAIL
      - MUST NOT return fail_closed=False unless BOTH steps succeed

    skill_orchestrated evidence path (P6 alignment):
      /code-review and /simplify are Claude Code slash commands, not PATH binaries —
      `which code-review` always fails. In the canonical /gd review flow the orchestrating
      Claude session runs both slash commands UPSTREAM, then passes their artifacts to the
      router via GD_UPSTREAM_QUALITY_EVIDENCE (a dir holding code-review + simplify logs).
      When that env points at a dir with both a `*code*review*` and a `*simplify*` artifact,
      the gate is satisfied (status="ok", origin="skill_orchestrated_evidence"). Absent that
      evidence AND with neither tool on PATH, the gate fail-closes as before — the fail-closed
      contract is preserved and the self-test still exercises the unavailable→fail_closed path.
    """
    import hashlib
    steps: list = []
    output_dir_path = Path(output_dir)

    # skill_orchestrated evidence: orchestrating session ran /code-review + /simplify upstream
    # and dropped their artifacts in a dir referenced by GD_UPSTREAM_QUALITY_EVIDENCE.
    evidence_dir = os.environ.get("GD_UPSTREAM_QUALITY_EVIDENCE", "").strip()

    def _evidence_for(step_name: str):
        """Return a matching evidence artifact Path for this step, or None.

        code-review step needs a file whose name contains both 'code' and 'review';
        simplify step needs a file whose name contains 'simplify'.
        """
        if not evidence_dir:
            return None
        d = Path(evidence_dir)
        if not d.is_dir():
            return None
        for p in sorted(d.iterdir()):
            if not p.is_file():
                continue
            name = p.name.lower()
            if step_name == "code-review" and "code" in name and "review" in name:
                return p
            if step_name == "simplify" and "simplify" in name:
                return p
        return None

    def _probe_tool(tool_name: str) -> bool:
        """Probe whether a tool is available (dry probe via which)."""
        try:
            r = subprocess.run(["which", tool_name], capture_output=True, text=True, timeout=5)
            return r.returncode == 0
        except Exception:
            return False

    def _run_step(step_name: str, tool_name: str, extra_args: list | None = None):
        log_path = output_dir_path / f"quality_gate_{step_name.replace('-', '_')}_{invocation_id}.log"
        # skill_orchestrated evidence short-circuit: if the orchestrating session already ran
        # this slash command upstream and supplied its artifact, accept it (status="ok") and
        # skip the PATH probe (slash commands are never on PATH).
        ev = _evidence_for(step_name)
        if ev is not None:
            try:
                ev_bytes = ev.read_bytes()
            except OSError:
                ev_bytes = b""
            ev_hash = hashlib.sha256(ev_bytes).hexdigest()
            steps.append({
                "step": step_name, "status": "ok",
                "exit_code": 0, "output_ref": str(ev),
                "output_hash": ev_hash, "origin": "skill_orchestrated_evidence",
            })
            return None, None  # evidence satisfied; out text not consumed by callers
        if not _probe_tool(tool_name):
            steps.append({
                "step": step_name, "status": "unavailable",
                "exit_code": -1, "output_ref": "", "output_hash": "",
            })
            unavail_code = f"{step_name.upper().replace('-', '_')}_UNAVAILABLE"
            return None, unavail_code
        try:
            cmd = [tool_name] + (extra_args or []) + [str(target)]
            r = subprocess.run(
                cmd, capture_output=True, text=True, timeout=300,
                cwd=str(output_dir_path.parent),
            )
            out = (r.stdout + r.stderr)[:4096]
            log_path.write_text(out, encoding="utf-8")
            out_hash = hashlib.sha256(out.encode()).hexdigest()
            status = "ok" if r.returncode == 0 else "failed"
            steps.append({
                "step": step_name, "status": status,
                "exit_code": r.returncode, "output_ref": str(log_path), "output_hash": out_hash,
            })
            if r.returncode != 0:
                return None, "UPSTREAM_QUALITY_GATE_FAIL"
            return None, None  # out text not consumed by callers
        except Exception as e:
            steps.append({
                "step": step_name, "status": "failed",
                "exit_code": -2, "output_ref": "", "output_hash": "",
            })
            return None, "UPSTREAM_QUALITY_GATE_FAIL"

    _, err1 = _run_step("code-review", "code-review")
    if err1:
        return {"steps": steps, "failure_code": err1, "fail_closed": True}

    _, err2 = _run_step("simplify", "simplify")
    if err2:
        return {"steps": steps, "failure_code": err2, "fail_closed": True}

    return {"steps": steps, "failure_code": None, "fail_closed": False}


def _get_plan_ref(outcome_path: Path) -> str | None:
    """SC-2 接线辅助：从 outcome JSON 读取 plan_ref 字段（可选）。
    存在且为字符串时返回路径；不存在或非字符串时返回 None（退回 Phase 1 纯格式校验）。
    HIGH-4 fix: reject non-string plan_ref (dict/list/bool) to avoid nonsense --plan-file arg.
    """
    try:
        data = json.loads(outcome_path.read_text(encoding="utf-8"))
        ref = data.get("plan_ref")
        if not ref:
            return None
        if not isinstance(ref, str):
            print(
                f"WARN: plan_ref in {outcome_path.name} is not a string "
                f"(got {type(ref).__name__!r}) — ignoring, Phase 1 only",
                file=sys.stderr,
            )
            return None
        return ref
    except Exception:
        return None


def _build_outcome_validator_cmd(
    outcome_script: Path, target: Path, plan_ref: str | None
) -> list[str]:
    """构造 outcome validator 调用命令；有 plan_ref 时激活 Phase 2 verify-rerun。"""
    cmd = [sys.executable, str(outcome_script), str(target)]
    if plan_ref:
        cmd += ["--plan-file", plan_ref]
    return cmd


def _run_live_execution_only(
    target: Path,
    output_dir: Path,
    invocation_id: str,
    codex_raw_result: Path | None = None,
    codex_mapped_result: Path | None = None,
    review_contract: str = "auto",
    live_bridge_timeout_sec: int = 360,
    use_controller: bool = False,
    claude_review_json: Path | None = None,
    deep: bool = False,
    plan_file: str | None = None,
) -> int:
    """execution_only_no_code (Execution-Review Cross-Review v2):
      Stage 1: invoke gd-validate-execution-outcome.py (validate facts/deliverables/verify-reruns)
      Stage 1.5 / Stage 2a — 两条收敛路径，由 use_controller 选择：
        · use_controller=True  → Stage 2a：gd-review-controller.py 多轮收敛（T7，/review2 code 驱动）
        · use_controller=False → Stage 1.5：上游质量门(/code-review + /simplify)，任一不可用/非零即 fail-closed
      Stage 2: invoke / consume Codex bridge 一致性 cross-review（验 review 质量 / SC / anti-fill）
      APPROVED requires all active-path stages pass; missing Codex → REQUIRES_CHANGES with codex_review_status.
    """
    import hashlib
    outcome_script = SCRIPTS / "gd-validate-execution-outcome.py"
    output_dir.mkdir(parents=True, exist_ok=True)
    plan_ref = _get_plan_ref(target)  # SC-2: read plan_ref for Phase 2 verify-rerun

    # T7: controller multi-round path — used when /review2 code drives the full loop.
    # Single-round path (codex_raw_result / codex_mapped_result injection) is preserved
    # for backward compat and fixture-based testing.
    if use_controller:
        # Stage 1: local outcome validator
        r_outcome = subprocess.run(
            _build_outcome_validator_cmd(outcome_script, target, plan_ref),
            capture_output=True, text=True,
            env={**os.environ, INVOCATION_ID_ENV: invocation_id},
        )
        if r_outcome.returncode != 0:
            print(
                f"ERROR: OUTCOME_VALIDATOR_FAIL: outcome validator failed before controller",
                file=sys.stderr,
            )
            return 1
        # Stage 2a: T7 controller multi-round loop
        return _run_controller_multi_round(
            branch="execution-only",
            target=target,
            output_dir=output_dir,
            invocation_id=invocation_id,
            execution_result=target,
            claude_review_json=claude_review_json,
            deep=deep,
            plan_file=plan_file,
        )

    # --- Stage 1: local outcome validator (validates facts) ---
    r_outcome = subprocess.run(
        _build_outcome_validator_cmd(outcome_script, target, plan_ref),
        capture_output=True, text=True,
        env={**os.environ, INVOCATION_ID_ENV: invocation_id},
    )
    exec_hash = hashlib.sha256(target.read_bytes()).hexdigest()

    if r_outcome.returncode != 0:
        # Outcome failed → Codex MUST NOT run; final REQUIRES_CHANGES.
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "execution_only_no_code",
            "decision": "REQUIRES_CHANGES",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "execution_artifact_ref": str(target),
            "execution_artifact_hash": exec_hash,
            "outcome_validator_status": "failed",
            "codex_review_status": "not_run_blocked",
            "codex_review_kind": "execution_outcome",
            "failure_code": "OUTCOME_VALIDATOR_FAIL",
            "claude_review_origin": "not_applicable",
            "findings": [{
                "reviewer": "outcome_validator",
                "severity": "error",
                "description": (r_outcome.stderr[:500] if r_outcome.stderr else "outcome validator failed"),
            }],
        }
        rc, _ = write_and_validate_route_report(report, output_dir)  # D2
        return 1  # outcome failed: no ledger needed (not APPROVED)

    # --- Stage 1.5: upstream quality gate (/code-review + /simplify) ---
    # fail-closed: any unavailability or non-zero exit short-circuits here (SC-1 / master SC-5)
    gate_result = _run_upstream_quality_gate(target, output_dir, invocation_id)
    if gate_result["fail_closed"]:
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "execution_only_no_code",
            "decision": "REQUIRES_CHANGES",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "execution_artifact_ref": str(target),
            "execution_artifact_hash": exec_hash,
            "outcome_validator_status": "passed",
            "codex_review_status": "not_run_blocked",
            "codex_review_kind": "execution_outcome",
            "codex_review_scope": "conformance",
            "failure_code": gate_result["failure_code"],
            "claude_review_origin": "not_applicable",
            "upstream_quality_gate": {"steps": gate_result["steps"], "fail_closed": True},
            "findings": [{
                "reviewer": "quality_gate",
                "severity": "error",
                "description": f"上游质量门失败: {gate_result['failure_code']}",
            }],
        }
        rc, _ = write_and_validate_route_report(report, output_dir)
        return 1  # fail-closed: upstream quality gate failed

    # Quality gate passed; record results and proceed to Codex conformance cross-review
    upstream_quality_gate_record = {"steps": gate_result["steps"], "fail_closed": False}

    # --- Stage 2: Codex bridge conformance cross-review (validates conformance to plan SC) ---
    # Codex task is scoped to conformance: verify implementation meets plan SC; not a full bug hunt.
    bridge_script = SCRIPTS / "gd-codex-bridge-review.py"
    codex_status = "not_run_blocked"
    codex_decision = None
    codex_raw_path = None
    codex_raw_hash = None
    codex_mapped_path = None
    codex_mapped_hash = None
    findings: list = []

    # Path A: caller injected raw fixture → parse-transport (offline)
    if codex_raw_result is not None:
        mapped_out = output_dir / f"codex_mapped_{invocation_id[-8:]}.json"
        parse_args = [
            sys.executable, str(bridge_script), "parse-transport",
            "--kind", "execution_outcome",
            "--target", str(target),
            "--raw-result", str(codex_raw_result),
            "--out", str(mapped_out),
        ]
        # revision=20: current Codex writer still outputs v1-style header
        # ("# Code Review Result") for execution kinds; always use --compat-v1
        # when parsing execution_outcome raw until writer migrates to v2 header.
        # Explicit "v2" contract overrides this to enforce v2 header strictly.
        if review_contract != "v2":
            parse_args.append("--compat-v1")
        if deep:
            parse_args.append("--deep")
        r_bridge = subprocess.run(parse_args, capture_output=True, text=True)
        if not mapped_out.exists():
            codex_status = "wrapper_schema_fail"
            findings.append({
                "reviewer": "codex_bridge",
                "severity": "error",
                "description": f"bridge parse-transport failed: {r_bridge.stderr[:400]}",
            })
        else:
            codex_raw_path = str(codex_raw_result)
            codex_raw_hash = hashlib.sha256(codex_raw_result.read_bytes()).hexdigest()
            codex_mapped_path = str(mapped_out)
            codex_mapped_hash = hashlib.sha256(mapped_out.read_bytes()).hexdigest()
            try:
                mapped = json.loads(mapped_out.read_text(encoding="utf-8"))
                codex_decision = mapped.get("gd_review_decision") or mapped.get("decision")
                # R1: derive codex_review_status from verdict + run_status via the shared
                # SSOT helper — a FAILED/degraded mapped must NOT silently become 'completed'.
                codex_status = codex_review_status_from_evidence(
                    True,
                    str(codex_decision).strip().upper() if codex_decision else "FAILED",
                    mapped.get("review_run_status"))
                for f in mapped.get("findings", []) or []:
                    findings.append({**f, "reviewer": "codex"})
            except Exception as e:
                codex_status = "wrapper_schema_fail"
                findings.append({"reviewer": "codex_bridge", "severity": "error",
                                 "description": f"mapped JSON unreadable: {e}"})
    # Path B: caller injected mapped fixture → use directly
    elif codex_mapped_result is not None:
        try:
            mapped = json.loads(codex_mapped_result.read_text(encoding="utf-8"))
            codex_decision = mapped.get("gd_review_decision") or mapped.get("decision")
            # R1: shared SSOT helper (verdict + run_status aware) instead of 2-state inline
            # that mapped FAILED/None/unknown → completed.
            codex_status = codex_review_status_from_evidence(
                True,
                str(codex_decision).strip().upper() if codex_decision else "FAILED",
                mapped.get("review_run_status"))
            codex_mapped_path = str(codex_mapped_result)
            codex_mapped_hash = hashlib.sha256(codex_mapped_result.read_bytes()).hexdigest()
            # raw_path unknown when only mapped supplied; mark synthetic
            codex_raw_path = str(codex_mapped_result) + ".raw_unknown"
            codex_raw_hash = "0" * 64
            for f in mapped.get("findings", []) or []:
                findings.append({**f, "reviewer": "codex"})
        except Exception as e:
            codex_status = "wrapper_schema_fail"
            findings.append({"reviewer": "codex_bridge", "severity": "error",
                             "description": f"mapped JSON unreadable: {e}"})
    # Path C: no injection → invoke _run_live_codex_bridge helper (C2 refactor).
    # Helper unifies run-bridge --live-transport + parse-transport for execution_outcome/combined.
    else:
        bridge_result = _run_live_codex_bridge(
            kind="execution_outcome",
            target=target,
            output_dir=output_dir,
            invocation_id=invocation_id,
            timeout_sec=live_bridge_timeout_sec,
            deep=deep,
            plan_file=plan_file,
        )
        codex_status = bridge_result["status"]
        codex_decision = bridge_result["decision"]
        codex_raw_path = bridge_result["raw_path"]
        codex_raw_hash = bridge_result["raw_hash"]
        codex_mapped_path = bridge_result["mapped_path"]
        codex_mapped_hash = bridge_result["mapped_hash"]
        findings.extend(bridge_result["findings"])

    # --- Decision merge: APPROVED requires outcome pass + quality gate pass + Codex conformance APPROVED ---
    if codex_status == "completed" and (codex_decision in (None, "APPROVED")):
        final_decision = "APPROVED"
    else:
        final_decision = "REQUIRES_CHANGES"

    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live",
        "review_target_kind": "execution_only_no_code",
        "decision": final_decision,
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "execution_artifact_ref": str(target),
        "execution_artifact_hash": exec_hash,
        "outcome_validator_status": "passed",
        "codex_review_kind": "execution_outcome",
        "codex_review_status": codex_status,
        # conformance scoping: Codex reviews whether implementation meets plan SC; not a full bug hunt (SC-2)
        "codex_review_scope": "conformance",
        "claude_review_origin": "not_applicable",
        # upstream quality gate results are separately observable (SC-2 separation requirement)
        "upstream_quality_gate": upstream_quality_gate_record,
        "findings": findings,
    }
    if codex_raw_path is not None:
        report["codex_raw_result_path"] = codex_raw_path
        report["codex_raw_result_hash"] = codex_raw_hash
    if codex_mapped_path is not None:
        report["codex_mapped_result_path"] = codex_mapped_path
        report["codex_mapped_result_hash"] = codex_mapped_hash
    if codex_status == "transport_failed":
        report["failure_code"] = "CODEX_TRANSPORT_UNAVAILABLE"
    elif codex_status == "wrapper_schema_fail":
        report["failure_code"] = "CODEX_WRAPPER_SCHEMA_FAIL"

    # D1: generate child review ledger (outcome_validator + codex_bridge as 2 child jobs)
    ledger_path = output_dir / f"child_review_ledger_execution_outcome_{invocation_id[-8:]}.json"
    report["child_review_ledger_path"] = str(ledger_path)

    # D2 + D1: the child ledger must exist before route-report validation. The
    # write -> ledger -> validate ordering is centralized in
    # write_and_validate_route_report (via ledger_writer) so this path — and any
    # future ledger-bearing path — cannot get the ordering wrong.
    def _write_ledger(rp):
        _write_execution_review_ledger(
            ledger_path=ledger_path,
            invocation_id=invocation_id,
            stage="review_execution_code",
            codex_review_kind="execution_outcome",
            outcome_validator_status="passed",
            exec_hash=exec_hash,
            target=target,
            codex_status=codex_status,
            codex_decision=codex_decision,
            codex_mapped_path=codex_mapped_path,
            codex_mapped_hash=codex_mapped_hash,
            codex_raw_path=codex_raw_path,
            codex_raw_hash=codex_raw_hash,
            route_report_path=rp,
            final_decision=final_decision,
        )

    rc, _ = write_and_validate_route_report(report, output_dir, ledger_writer=_write_ledger)
    if rc != 0:  # propagate validator rc
        return 1
    return 0 if final_decision == "APPROVED" else 1


def _run_live_code_only(
    target: Path,
    output_dir: Path,
    invocation_id: str,
) -> int:
    """code_only: LOCAL_STATIC_ONLY — delegated to skill_orchestrated Claude (3a-SC-5/SC-9).
    Must not claim active/live Codex sidecar.
    Stage 1: upstream quality gate (/code-review + /simplify); fail-closed if either unavailable/non-zero
    Stage 2: skill_orchestrated Claude static review (LOCAL_STATIC_ONLY)
    handler = skill_orchestrated Claude static review
    allowed decisions = APPROVED | REQUIRES_CHANGES | FAILED (failure_code=LOCAL_STATIC_ONLY)
    Always exits 1 (REQUIRES_CHANGES) since actual review done by skill_orchestrated Claude."""
    import hashlib
    output_dir.mkdir(parents=True, exist_ok=True)
    # Compute diff for audit trail
    try:
        cwd = str(target.parent if target.is_file() else target)
        r_diff = subprocess.run(
            ["git", "diff", "HEAD", "--", str(target)],
            capture_output=True, text=True, cwd=cwd,
        )
        diff_content = r_diff.stdout if r_diff.stdout else f"# no diff output; git exit={r_diff.returncode}; target={target}"
    except Exception as e:
        diff_content = f"# git diff unavailable: {e}"
    diff_hash = hashlib.sha256(diff_content.encode()).hexdigest()
    diff_path = output_dir / f"code_diff_{invocation_id[-8:]}.patch"
    diff_path.write_text(diff_content, encoding="utf-8")

    # --- Stage 1: upstream quality gate (/code-review + /simplify) after diff landing ---
    # fail-closed: any unavailability or non-zero exit short-circuits here (SC-1 / master SC-5)
    gate_result = _run_upstream_quality_gate(target, output_dir, invocation_id)
    if gate_result["fail_closed"]:
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "code_only",
            "decision": "REQUIRES_CHANGES",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "diff_source": f"git diff HEAD -- {target}",
            "diff_hash": diff_hash,
            "patch_generation_method": "git_diff",
            "raw_result_path": str(diff_path),
            "raw_result_hash": diff_hash,
            "claude_review_origin": "skill_orchestrated",
            "failure_code": gate_result["failure_code"],
            "upstream_quality_gate": {"steps": gate_result["steps"], "fail_closed": True},
            "findings": [{
                "reviewer": "quality_gate",
                "severity": "error",
                "description": f"上游质量门失败: {gate_result['failure_code']}",
            }],
        }
        write_and_validate_route_report(report, output_dir)
        return 1  # fail-closed: upstream quality gate failed

    # Quality gate passed; record results and proceed to Codex conformance cross-review (SC-2)
    # codex_review_scope="conformance": Codex verifies implementation meets plan SC, not a full bug hunt
    upstream_quality_gate_record = {"steps": gate_result["steps"], "fail_closed": False}

    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live",
        "review_target_kind": "code_only",
        "decision": "REQUIRES_CHANGES",
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "diff_source": f"git diff HEAD -- {target}",
        "diff_hash": diff_hash,
        "patch_generation_method": "git_diff",
        "raw_result_path": str(diff_path),
        "raw_result_hash": diff_hash,
        "claude_review_origin": "skill_orchestrated",
        # conformance scoping: Codex reviews whether implementation meets plan SC (SC-2)
        "codex_review_scope": "conformance",
        "failure_code": "LOCAL_STATIC_ONLY",
        # upstream quality gate results are separately observable (SC-2 separation requirement)
        "upstream_quality_gate": upstream_quality_gate_record,
        "findings": [{
            "reviewer": "router",
            "severity": "info",
            "description": (
                "code_only: static review delegated to skill_orchestrated Claude. "
                "Router records diff for audit trail; Codex code sidecar NOT active (3a-SC-9). "
                "REQUIRES_CHANGES until skill_orchestrated review completes."
            ),
        }],
    }
    # L3 content-evidence validation note (SC-W2-2):
    # code_only router does not have a real Codex review to validate at this stage.
    # The diff_path is the diff itself, not a review output. L3 would be a no-op
    # (target == review). The actual L3 gate runs in parse-transport when Codex
    # returns a real review result. No L3 call here prevents the no-op false pass.

    write_and_validate_route_report(report, output_dir)
    return 1  # REQUIRES_CHANGES — actual verdict from skill_orchestrated review


def _run_live_execution_plus_code(
    target: Path,
    output_dir: Path,
    invocation_id: str,
    codex_raw_result: Path | None = None,
    codex_mapped_result: Path | None = None,
    review_contract: str = "auto",
    live_bridge_timeout_sec: int = 360,
    use_controller: bool = False,
    claude_review_json: Path | None = None,
    deep: bool = False,
    plan_file: str | None = None,
) -> int:
    """execution_plus_code (combined): outcome-first, then code if passes (3a-SC-5/SC-7).
    Stage 1: gd-validate-execution-outcome.py
    Stage 2a (T7 controller path): multi-round convergence loop via gd-review-controller.py
             --branch combined (use_controller=True).
    Stage 2b (single-round path): LOCAL_STATIC_ONLY code review (skill_orchestrated) — backward compat.
    """
    import hashlib
    # If target is a directory, resolve to the first valid execution JSON within it
    # (execution_plus_code detection requires a dir with both .md + exec JSON, but
    # outcome validator and _get_plan_ref need a concrete file).
    if target.is_dir():
        for candidate in sorted(target.rglob("*.json")):
            if candidate.name.startswith("_"):
                continue
            if is_execution_json(candidate):
                target = candidate
                break
    plan_ref = _get_plan_ref(target)  # SC-2: read plan_ref for Phase 2 verify-rerun
    outcome_script = SCRIPTS / "gd-validate-execution-outcome.py"  # hoisted; used in both branches

    # T7: controller combined-branch path
    if use_controller:
        r_outcome = subprocess.run(
            _build_outcome_validator_cmd(outcome_script, target, plan_ref),
            capture_output=True, text=True,
            env={**os.environ, INVOCATION_ID_ENV: invocation_id},
        )
        if r_outcome.returncode != 0:
            print(
                "ERROR: OUTCOME_FIRST_FAIL: outcome validator failed before combined controller",
                file=sys.stderr,
            )
            return 1
        return _run_controller_multi_round(
            branch="combined",
            target=target,
            output_dir=output_dir,
            invocation_id=invocation_id,
            execution_result=target,
            claude_review_json=claude_review_json,
            deep=deep,
            plan_file=plan_file,
        )

    r_outcome = subprocess.run(
        _build_outcome_validator_cmd(outcome_script, target, plan_ref),
        capture_output=True, text=True,
        env={**os.environ, INVOCATION_ID_ENV: invocation_id},
    )

    if r_outcome.returncode != 0:
        # Outcome failed → OUTCOME_FIRST_FAIL; code review MUST NOT run (3a-SC-7)
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "execution_plus_code",
            "decision": "FAILED",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "execution_artifact_ref": str(target),
            "outcome_validator_status": "not_run_blocked",
            "stage_order": ["outcome", "code"],
            "failure_code": "OUTCOME_FIRST_FAIL",
            "claude_review_origin": "not_applicable",
            "findings": [{
                "reviewer": "outcome_validator",
                "severity": "error",
                "description": (
                    "outcome validation failed; code review BLOCKED per outcome-first rule (3a-SC-7). "
                    + (r_outcome.stderr[:400] if r_outcome.stderr else "")
                ),
            }],
        }
        rc, _ = write_and_validate_route_report(report, output_dir)  # D2
        return 1  # outcome failed: no ledger needed (not APPROVED)

    # Outcome passed → Stage 1.5: upstream quality gate (/code-review + /simplify)
    # fail-closed: any unavailability or non-zero exit short-circuits here (SC-1 / master SC-5)
    output_dir.mkdir(parents=True, exist_ok=True)
    exec_hash = hashlib.sha256(target.read_bytes()).hexdigest()

    gate_result = _run_upstream_quality_gate(target, output_dir, invocation_id)
    if gate_result["fail_closed"]:
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "execution_plus_code",
            "decision": "REQUIRES_CHANGES",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "execution_artifact_ref": str(target),
            "execution_artifact_hash": exec_hash,
            "outcome_validator_status": "passed",
            "codex_review_status": "not_run_blocked",
            "codex_review_kind": "combined",
            "codex_review_scope": "conformance",
            "stage_order": ["outcome", "code"],
            "failure_code": gate_result["failure_code"],
            "claude_review_origin": "not_applicable",
            "upstream_quality_gate": {"steps": gate_result["steps"], "fail_closed": True},
            "findings": [{
                "reviewer": "quality_gate",
                "severity": "error",
                "description": f"上游质量门失败: {gate_result['failure_code']}",
            }],
        }
        rc, _ = write_and_validate_route_report(report, output_dir)
        return 1  # fail-closed: upstream quality gate failed

    # Quality gate passed; record results and proceed to Codex conformance cross-review (SC-2)
    upstream_quality_gate_record = {"steps": gate_result["steps"], "fail_closed": False}

    # Stage 2: combined Codex conformance cross-review (Execution-Review Cross-Review v2)
    # Codex task is scoped to conformance: verify implementation meets plan SC; not a full bug hunt.
    bridge_script = SCRIPTS / "gd-codex-bridge-review.py"
    codex_status = "not_run_blocked"
    codex_decision = None
    codex_raw_path = None
    codex_raw_hash = None
    codex_mapped_path = None
    codex_mapped_hash = None
    findings: list = []

    if codex_raw_result is not None:
        mapped_out = output_dir / f"codex_combined_mapped_{invocation_id[-8:]}.json"
        parse_args = [
            sys.executable, str(bridge_script), "parse-transport",
            "--kind", "combined",
            "--target", str(target),
            "--raw-result", str(codex_raw_result),
            "--out", str(mapped_out),
        ]
        # revision=20: same compat-v1 policy as execution_only path
        if review_contract != "v2":
            parse_args.append("--compat-v1")
        if deep:
            parse_args.append("--deep")
        r_bridge = subprocess.run(parse_args, capture_output=True, text=True)
        if not mapped_out.exists():
            codex_status = "wrapper_schema_fail"
            findings.append({"reviewer": "codex_bridge", "severity": "error",
                             "description": f"bridge parse-transport failed: {r_bridge.stderr[:400]}"})
        else:
            codex_raw_path = str(codex_raw_result)
            codex_raw_hash = hashlib.sha256(codex_raw_result.read_bytes()).hexdigest()
            codex_mapped_path = str(mapped_out)
            codex_mapped_hash = hashlib.sha256(mapped_out.read_bytes()).hexdigest()
            try:
                mapped = json.loads(mapped_out.read_text(encoding="utf-8"))
                codex_decision = mapped.get("gd_review_decision") or mapped.get("decision")
                # R1: derive codex_review_status from verdict + run_status via the shared
                # SSOT helper — a FAILED/degraded mapped must NOT silently become 'completed'.
                codex_status = codex_review_status_from_evidence(
                    True,
                    str(codex_decision).strip().upper() if codex_decision else "FAILED",
                    mapped.get("review_run_status"))
                for f in mapped.get("findings", []) or []:
                    findings.append({**f, "reviewer": "codex"})
            except Exception as e:
                codex_status = "wrapper_schema_fail"
                findings.append({"reviewer": "codex_bridge", "severity": "error",
                                 "description": f"mapped JSON unreadable: {e}"})
    elif codex_mapped_result is not None:
        try:
            mapped = json.loads(codex_mapped_result.read_text(encoding="utf-8"))
            codex_decision = mapped.get("gd_review_decision") or mapped.get("decision")
            # R1: shared SSOT helper (verdict + run_status aware) instead of 2-state inline
            # that mapped FAILED/None/unknown → completed.
            codex_status = codex_review_status_from_evidence(
                True,
                str(codex_decision).strip().upper() if codex_decision else "FAILED",
                mapped.get("review_run_status"))
            codex_mapped_path = str(codex_mapped_result)
            codex_mapped_hash = hashlib.sha256(codex_mapped_result.read_bytes()).hexdigest()
            codex_raw_path = str(codex_mapped_result) + ".raw_unknown"
            codex_raw_hash = "0" * 64
            for f in mapped.get("findings", []) or []:
                findings.append({**f, "reviewer": "codex"})
        except Exception as e:
            codex_status = "wrapper_schema_fail"
            findings.append({"reviewer": "codex_bridge", "severity": "error",
                             "description": f"mapped JSON unreadable: {e}"})
    else:
        # C3: no injection → call live bridge with kind=combined (was transport_failed).
        bridge_result = _run_live_codex_bridge(
            kind="combined",
            target=target,
            output_dir=output_dir,
            invocation_id=invocation_id,
            timeout_sec=live_bridge_timeout_sec,
            deep=deep,
            plan_file=plan_file,
        )
        codex_status = bridge_result["status"]
        codex_decision = bridge_result["decision"]
        codex_raw_path = bridge_result["raw_path"]
        codex_raw_hash = bridge_result["raw_hash"]
        codex_mapped_path = bridge_result["mapped_path"]
        codex_mapped_hash = bridge_result["mapped_hash"]
        findings.extend(bridge_result["findings"])

    final_decision = "APPROVED" if (codex_status == "completed" and codex_decision in (None, "APPROVED")) else "REQUIRES_CHANGES"

    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live",
        "review_target_kind": "execution_plus_code",
        "decision": final_decision,
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "execution_artifact_ref": str(target),
        "execution_artifact_hash": exec_hash,
        "outcome_validator_status": "passed",
        "stage_order": ["outcome", "code"],
        "codex_review_kind": "combined",
        "codex_review_status": codex_status,
        # conformance scoping: Codex reviews whether implementation meets plan SC (SC-2)
        "codex_review_scope": "conformance",
        "claude_review_origin": "not_applicable",
        # upstream quality gate results are separately observable (SC-2 separation requirement)
        "upstream_quality_gate": upstream_quality_gate_record,
        "findings": findings,
    }
    if codex_raw_path is not None:
        report["codex_raw_result_path"] = codex_raw_path
        report["codex_raw_result_hash"] = codex_raw_hash
    if codex_mapped_path is not None:
        report["codex_mapped_result_path"] = codex_mapped_path
        report["codex_mapped_result_hash"] = codex_mapped_hash
    if codex_status == "transport_failed":
        report["failure_code"] = "CODEX_TRANSPORT_UNAVAILABLE"
    elif codex_status == "wrapper_schema_fail":
        report["failure_code"] = "CODEX_WRAPPER_SCHEMA_FAIL"

    # D1: generate child review ledger (outcome_validator + codex_bridge as 2 child jobs)
    ledger_path = output_dir / f"child_review_ledger_combined_{invocation_id[-8:]}.json"
    report["child_review_ledger_path"] = str(ledger_path)

    # D2 + D1: the child ledger must exist before route-report validation. The
    # write -> ledger -> validate ordering is centralized in
    # write_and_validate_route_report (via ledger_writer) so this path — and any
    # future ledger-bearing path — cannot get the ordering wrong.
    def _write_ledger(rp):
        _write_execution_review_ledger(
            ledger_path=ledger_path,
            invocation_id=invocation_id,
            stage="review_execution_code",
            codex_review_kind="combined",
            outcome_validator_status="passed",
            exec_hash=exec_hash,
            target=target,
            codex_status=codex_status,
            codex_decision=codex_decision,
            codex_mapped_path=codex_mapped_path,
            codex_mapped_hash=codex_mapped_hash,
            codex_raw_path=codex_raw_path,
            codex_raw_hash=codex_raw_hash,
            route_report_path=rp,
            final_decision=final_decision,
        )

    rc, _ = write_and_validate_route_report(report, output_dir, ledger_writer=_write_ledger)
    if rc != 0:  # propagate validator rc
        return 1
    return 0 if final_decision == "APPROVED" else 1


def run_live(
    target: Path | None,
    output_dir: Path,
    invocation_id: str,
    claude_review: str | None = None,
    codex_raw_result: str | None = None,
    codex_mapped_result: str | None = None,
    review_contract: str = 'auto',
    expected_target_hash: str | None = None,
    live_bridge_timeout_sec: int = 360,
    deep: bool = False,
    plan_file: str | None = None,
) -> int:
    print(f"=== gd-review-router: live mode ===")
    print(f"target    : {target or '(auto)'}")
    print()

    kind = detect_review_target_kind(target)
    print(f"detected target kind: {kind}")

    # P2 fail-closed: a self-declared-but-corrupt router descriptor is reported
    # with a DISTINCT failure_code from a genuine no-artifact target, so the
    # operator can tell "you pointed at a broken descriptor" apart from "there
    # was nothing to review". Both still fail-closed (exit 2, never APPROVE).
    if kind == CORRUPT_DESCRIPTOR_SENTINEL:
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "no_artifact",
            "decision": "REVIEW_TARGET_MISSING",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "failure_code": "CORRUPT_ROUTER_DESCRIPTOR",
            "claude_review_origin": "not_applicable",
            "findings": [{"reviewer": "router", "severity": "error",
                          "description": "CORRUPT_ROUTER_DESCRIPTOR: target declared a v1 router "
                                         "descriptor (router_version + artifacts) but it is "
                                         "unreadable/malformed; fail-closed, distinct from "
                                         "NO_ARTIFACT_DETECTED. Must not APPROVE."}],
        }
        write_and_validate_route_report(report, output_dir)
        print("ERROR: CORRUPT_ROUTER_DESCRIPTOR: descriptor present but malformed; fail-closed",
              file=sys.stderr)
        return 2

    if kind == "no_artifact":
        report = {
            "schema_version": "2.0",
            "router_invocation_id": invocation_id,
            "mode": "live",
            "review_target_kind": "no_artifact",
            "decision": "REVIEW_TARGET_MISSING",
            "validator_signature": VALIDATOR_SIGNATURE,
            "recorded_at": now_iso(),
            "failure_code": "NO_ARTIFACT_DETECTED",
            "claude_review_origin": "not_applicable",
            "findings": [{"reviewer": "router", "severity": "error",
                          "description": "REVIEW_TARGET_MISSING: no reviewable artifact detected; "
                                         "fail-closed (3a-SC-6). Must not APPROVE."}],
        }
        write_and_validate_route_report(report, output_dir)
        print("ERROR: REVIEW_TARGET_MISSING: no reviewable artifact detected; fail-closed", file=sys.stderr)
        return 2  # exit 2 = missing input / no artifact (3a-SC-4/SC-6)

    # Plan 1: plan_only kind can be handled via subprocess merge loop with Claude + Codex inputs
    if kind == "plan_only" and target is not None:
        return _run_live_plan_review(
            target=target,
            output_dir=output_dir,
            invocation_id=invocation_id,
            claude_review=claude_review,
            codex_raw_result=codex_raw_result,
            codex_mapped_result=codex_mapped_result,
            review_contract=review_contract,
            expected_target_hash=expected_target_hash,
        )

    # Plan 3a: non-plan target kinds — all have defined live behavior (3a-SC-5).
    # No NOT_IMPLEMENTED. Handlers below.
    # Injected raw/mapped (offline/fixture) → single-round consume (Path A/B);
    # only drive the T7 multi-round controller when nothing was injected (true live).
    # Named once so the two execution handlers below cannot drift.
    is_true_live = codex_raw_result is None and codex_mapped_result is None
    if kind == "execution_only_no_code" and target is not None:
        return _run_live_execution_only(
            target, output_dir, invocation_id,
            codex_raw_result=(Path(codex_raw_result) if codex_raw_result else None),
            codex_mapped_result=(Path(codex_mapped_result) if codex_mapped_result else None),
            review_contract=review_contract,
            live_bridge_timeout_sec=live_bridge_timeout_sec,
            use_controller=is_true_live,
            deep=deep,
            plan_file=plan_file,
        )

    if kind == "code_only" and target is not None:
        return _run_live_code_only(target, output_dir, invocation_id)

    if kind == "execution_plus_code" and target is not None:
        return _run_live_execution_plus_code(
            target, output_dir, invocation_id,
            codex_raw_result=(Path(codex_raw_result) if codex_raw_result else None),
            codex_mapped_result=(Path(codex_mapped_result) if codex_mapped_result else None),
            review_contract=review_contract,
            live_bridge_timeout_sec=live_bridge_timeout_sec,
            use_controller=is_true_live,
            deep=deep,
            plan_file=plan_file,
        )

    # Fallback: target is None for a non-plan kind — fail-closed.
    report = {
        "schema_version": "2.0",
        "router_invocation_id": invocation_id,
        "mode": "live",
        "review_target_kind": kind,
        "decision": "FAILED",
        "validator_signature": VALIDATOR_SIGNATURE,
        "recorded_at": now_iso(),
        "failure_code": "TARGET_REQUIRED_FOR_KIND",
        "claude_review_origin": "not_applicable",
        "findings": [{"reviewer": "router", "severity": "error",
                      "description": f"live mode: --target required for kind={kind}"}],
    }
    if kind in ("execution_only_no_code", "execution_plus_code"):
        report["execution_artifact_ref"] = "(missing)"
        report["outcome_validator_status"] = "not_run_blocked"
    if kind == "execution_plus_code":
        report["stage_order"] = ["outcome", "code"]
    write_and_validate_route_report(report, output_dir)
    return 1


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

def run_self_test() -> int:
    errors: list[str] = []

    print("=== gd-review-router self-test ===")

    # 1. Route report validator exists
    if not ROUTE_REPORT_VALIDATOR.exists():
        errors.append(f"ROUTE_REPORT_VALIDATOR missing: {ROUTE_REPORT_VALIDATOR}")
    else:
        print(f"  route report validator present ✓")

    # 2. fixtures/review-router-v2/ exists and has content
    if not FIXTURES_V2.exists():
        errors.append(f"FIXTURES_V2 dir missing: {FIXTURES_V2}")
    else:
        v2_files = list(FIXTURES_V2.glob("*.json"))
        if not v2_files:
            errors.append(f"FIXTURES_V2 dir empty: {FIXTURES_V2}")
        else:
            print(f"  v2 fixtures: {len(v2_files)} files ✓")

    # 3. Q3 env check: INVOCATION_ID_ENV must be absent on entry
    if os.environ.get(INVOCATION_ID_ENV):
        errors.append(
            f"SIDE_DOOR_DETECTED: {INVOCATION_ID_ENV} is set; "
            "self-test should not be called from within a router run"
        )
    else:
        print(f"  Q3 side-door env absent ✓")

    # 4. Smoke: fixture mode with a known-good fixture
    good_fx = FIXTURES_V2 / "plan-only-approved.json"
    if good_fx.exists():
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            iid = generate_invocation_id()
            rc = run_fixture(good_fx, Path(td), iid)
        if rc == 0:
            print(f"  fixture smoke (plan-only-approved): PASS ✓")
        else:
            errors.append("fixture smoke (plan-only-approved) FAIL")
    else:
        errors.append(f"smoke fixture not found: {good_fx}")

    # 5. Upstream quality gate self-test (SC-1 behavior verification):
    #    Simulate /code-review unavailable scenario → must produce fail_closed=True.
    #    This is the behavioral verification for the fail-closed contract (SC-1 / master SC-5).
    import tempfile
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        iid_gate = "self-test-001"
        # _run_upstream_quality_gate probes via `which code-review` / `which simplify`.
        # On most systems neither is on PATH → status="unavailable" → fail_closed=True.
        # On systems where one/both exist, they may succeed or fail; we accept both outcomes:
        #   - fail_closed=True (either unavailable or non-zero): SC-1 contract satisfied.
        #   - fail_closed=False (both tools available AND both succeed): tools present, also valid.
        gate = _run_upstream_quality_gate(Path("."), tmp_path, iid_gate)
        if gate["fail_closed"]:
            fc_code = gate.get("failure_code", "")
            if fc_code in ("CODE_REVIEW_UNAVAILABLE", "SIMPLIFY_UNAVAILABLE", "UPSTREAM_QUALITY_GATE_FAIL"):
                print(f"  upstream quality gate fail-closed self-test: PASS (fail_closed=True, failure_code={fc_code}) ✓")
            else:
                errors.append(
                    f"upstream quality gate self-test FAIL: fail_closed=True but unexpected failure_code={fc_code!r}"
                )
        else:
            # Both tools are available and succeeded — also a valid production state.
            print(f"  upstream quality gate self-test: PASS (tools available, both succeeded) ✓")

    if errors:
        print("\nSELF_TEST FAIL:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1
    print("\nSELF_TEST: PASS")
    return 0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run_review_subcommand(sub: str, rest: list[str]) -> int:
    """SC-9/SC-17/SC-25: `review execution|code [--deep --plan-file --out --target]` subcommand.

    Thin wrapper over _run_live_codex_bridge that forces the review kind:
      review execution → execution_outcome
      review code      → code_diff
    Sets the G1 sentinel invocation id, runs the live deep bridge, and writes the
    mapped result JSON to --out (single file). Fails closed (non-zero) if the bridge
    does not produce a mapped result — never writes a pass result on transport failure.
    """
    kind = "execution_outcome" if sub == "execution" else "code_diff"
    sp = argparse.ArgumentParser(prog=f"gd-review-router.py review {sub}")
    sp.add_argument("--target", required=True, help="Review target (outcome JSON or code path)")
    sp.add_argument("--out", required=True, help="Single-file path to write mapped result JSON")
    sp.add_argument("--deep", action="store_true", default=False,
                    help="Deep review mode (workspace-write sandbox; bridge timeout ≥1800s)")
    sp.add_argument("--plan-file", default=None, help="Plan file for deep outcome capsule (plan-derived verify)")
    sp.add_argument("--output-dir", default=None, help="Working dir for intermediate bridge artifacts")
    sp.add_argument("--live-bridge-timeout-sec", type=int, default=360)
    a = sp.parse_args(rest)

    if os.environ.get(INVOCATION_ID_ENV):
        return err("SIDE_DOOR_DETECTED",
                   f"{INVOCATION_ID_ENV} already set; unset before invoking router subcommand", 2)

    invocation_id = generate_invocation_id()
    out_path = Path(a.out)
    work_dir = Path(a.output_dir) if a.output_dir else out_path.parent / f".review-{sub}-{invocation_id[-8:]}"
    work_dir.mkdir(parents=True, exist_ok=True)
    os.environ[INVOCATION_ID_ENV] = invocation_id
    try:
        res = _run_live_codex_bridge(
            kind=kind, target=Path(a.target), output_dir=work_dir,
            invocation_id=invocation_id,
            timeout_sec=a.live_bridge_timeout_sec,
            deep=a.deep, plan_file=a.plan_file,
        )
    finally:
        os.environ.pop(INVOCATION_ID_ENV, None)

    # Fail closed: no mapped result → do not write a pass outcome
    mapped_path = res.get("mapped_path")
    if not mapped_path or not Path(mapped_path).exists():
        print(f"REVIEW_SUBCOMMAND_FAILED: {sub} — {res.get('failure_description') or res.get('status')}",
              file=sys.stderr)
        return 1
    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(Path(mapped_path).read_text(encoding="utf-8"), encoding="utf-8")
    except OSError as exc:
        print(f"REVIEW_SUBCOMMAND_WRITE_ERROR: {exc}", file=sys.stderr)
        return 1
    decision = res.get("decision")
    print(f"REVIEW_SUBCOMMAND: {sub}")
    print(f"GD_REVIEW_DECISION: {decision}")
    print(f"MAPPED_RESULT: {out_path}")
    return 0 if decision == "APPROVED" else 1


def main() -> int:
    # SC-9: `review execution|code ...` subcommand form (translated to live deep bridge).
    # Must run BEFORE the side-door check because the subcommand sets the invocation id itself.
    argv = sys.argv[1:]
    if len(argv) >= 2 and argv[0] == "review" and argv[1] in ("execution", "code"):
        return run_review_subcommand(argv[1], argv[2:])

    # Q3: refuse if the invocation ID env is already set (side-door prevention)
    if os.environ.get(INVOCATION_ID_ENV):
        print(
            f"ERROR: SIDE_DOOR_DETECTED: {INVOCATION_ID_ENV}={os.environ[INVOCATION_ID_ENV]!r} "
            f"is set on entry — the router must not be called from within another router run. "
            f"Unset {INVOCATION_ID_ENV} before invoking directly.",
            file=sys.stderr,
        )
        return 2

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--mode", choices=sorted(VALID_MODES), help="Router execution mode (required unless --self-test)")
    p.add_argument("--fixture", help="Path to fixture JSON (required for --mode fixture)")
    p.add_argument("--target", help="Path to review target (plan file or directory)")
    p.add_argument("--output-dir", default=None, help="Directory to write route_report.json (default: GD_ROOT/reports/review-router/)")
    p.add_argument("--invocation-id", default=None, help="Optional router invocation ID (auto-generated if absent)")
    p.add_argument("--self-test", action="store_true", help="Run self-test and exit")
    p.add_argument("--claude-review", default=None, metavar="CLAUDE_JSON",
                   help="(live plan mode) Path to Claude review mapped JSON.")
    p.add_argument("--codex-raw-result", default=None, metavar="RAW_MD",
                   help="(live plan mode) Path to existing Codex raw .result file (read-only).")
    p.add_argument("--codex-mapped-result", default=None, metavar="MAPPED_JSON",
                   help="(live plan mode) Path to pre-mapped Codex result JSON.")
    p.add_argument("--review-contract", default="auto", choices=["auto", "v1", "v2"],
                   help="Raw result parse contract for --codex-raw-result (default: auto).")
    p.add_argument("--expected-target-hash", default=None, metavar="HASH",
                   help="SHA-256 of plan at review submit time for binding check.")
    p.add_argument("--live-bridge-timeout-sec", type=int, default=360, metavar="SEC",
                   help="Timeout (seconds) for live Codex bridge run-bridge subprocess. "
                        "Default 360 (codex-send-wait default is 300; must be longer). "
                        "On timeout: codex_review_status=transport_failed fail-closed.")
    p.add_argument("--deep", action="store_true", default=False,
                   help="SC-9: deep review mode; bridge timeout ≥1800s")
    p.add_argument("--plan-file", default=None,
                   help="SC-33: plan file path for deep outcome capsule")
    args = p.parse_args()

    if args.self_test:
        return run_self_test()

    if not args.mode:
        p.print_help()
        return 2

    invocation_id = args.invocation_id or generate_invocation_id()
    output_dir = Path(args.output_dir) if args.output_dir else GD_ROOT / "reports" / "review-router"
    target = Path(args.target) if args.target else None

    # Set invocation ID for downstream scripts (Q3: they can verify they're called from router)
    os.environ[INVOCATION_ID_ENV] = invocation_id

    if args.mode == "fixture":
        if not args.fixture:
            return err("FIXTURE_REQUIRED", "--fixture <path> is required for --mode fixture", 2)
        return run_fixture(Path(args.fixture), output_dir, invocation_id)
    elif args.mode == "detect_only":
        return run_detect_only(target, output_dir, invocation_id)
    elif args.mode == "live_dry_run":
        return run_live_dry_run(target, output_dir, invocation_id)
    elif args.mode == "live":
        return run_live(
            target, output_dir, invocation_id,
            claude_review=getattr(args, "claude_review", None),
            codex_raw_result=getattr(args, "codex_raw_result", None),
            codex_mapped_result=getattr(args, "codex_mapped_result", None),
            review_contract=getattr(args, "review_contract", "auto"),
            expected_target_hash=getattr(args, "expected_target_hash", None),
            live_bridge_timeout_sec=getattr(args, "live_bridge_timeout_sec", 360),
            deep=getattr(args, "deep", False),
            plan_file=getattr(args, "plan_file", None),
        )

    return err("UNKNOWN_MODE", args.mode, 2)


if __name__ == "__main__":
    sys.exit(main())
